/**
 * TSL ランク 1-250 (basicWordList) と 251-500 (vocabulary600) を生成するスクリプト
 * 既存の100語をベースに、TSL頻度順に近い形で250語ずつ拡張（重複なし）
 * 出力: wordList.js の basicWordList 部分、wordList630.js の vocabulary600 部分
 */

const fs = require('fs');
const path = require('path');

// TSL 101-250 用の150語（basicWordList 拡張分）[en, ja, romaji, pos]
const BASIC_EXTRA = [
  ["information", "じょうほう", "jouhou", "名詞"],
  ["process", "ぷろせす", "purosesu", "名詞"],
  ["system", "しすてむ", "shisutemu", "名詞"],
  ["policy", "ほうしん", "houshin", "名詞"],
  ["price", "ねだん", "nedan", "名詞"],
  ["result", "けっか", "kekka", "名詞"],
  ["role", "やくわり", "yakuwari", "名詞"],
  ["number", "かず", "kazu", "名詞"],
  ["area", "ちいき", "chiiki", "名詞"],
  ["plan", "けいかく", "keikaku", "名詞"],
  ["program", "ぷろぐらむ", "puroguramu", "名詞"],
  ["research", "けんきゅう", "kenkyuu", "名詞"],
  ["staff", "しょくいん", "shokuin", "名詞"],
  ["support", "しえん", "shien", "名詞"],
  ["training", "くんれん", "kunren", "名詞"],
  ["level", "すいじゅん", "suijun", "名詞"],
  ["type", "しゅるい", "shurui", "名詞"],
  ["rate", "りつ", "ritsu", "名詞"],
  ["risk", "りすく", "risuku", "名詞"],
  ["value", "かち", "kachi", "名詞"],
  ["action", "こうどう", "koudou", "名詞"],
  ["activity", "かつどう", "katsudou", "名詞"],
  ["amount", "がく", "gaku", "名詞"],
  ["approach", "あぷろーち", "apuroochi", "名詞"],
  ["assessment", "ひょうか", "hyouka", "名詞"],
  ["authority", "けんげん", "kengen", "名詞"],
  ["balance", "ばらんす", "baransu", "名詞"],
  ["basis", "きそ", "kiso", "名詞"],
  ["benefit", "りえき", "rieki", "名詞"],
  ["category", "かてごりー", "kategori", "名詞"],
  ["change", "へんこう", "henkou", "名詞"],
  ["choice", "せんたく", "sentaku", "名詞"],
  ["comment", "こめんと", "komento", "名詞"],
  ["commission", "こみっしょん", "komisshon", "名詞"],
  ["commitment", "こみっとめんと", "komittomento", "名詞"],
  ["community", "こみゅにてぃ", "komyuniti", "名詞"],
  ["comparison", "ひかく", "hikaku", "名詞"],
  ["competition", "きょうそう", "kyousou", "名詞"],
  ["complex", "ふくざつな", "fukuzatsu na", "形容詞"],
  ["concept", "がいねん", "gainen", "名詞"],
  ["concern", "しんぱい", "shinpai", "名詞"],
  ["conclusion", "けつろん", "ketsuron", "名詞"],
  ["confidence", "しんらい", "shinrai", "名詞"],
  ["conflict", "たいりつ", "tairitsu", "名詞"],
  ["connection", "せつぞく", "setsuzoku", "名詞"],
  ["consequence", "けっか", "kekka", "名詞"],
  ["consideration", "けんりょう", "kenryou", "名詞"],
  ["constant", "じょうすう", "jousuu", "名詞"],
  ["construction", "けんせつ", "kensetsu", "名詞"],
  ["context", "ぶんみゃく", "bunmyaku", "名詞"],
  ["control", "こんとろーる", "kontorooru", "名詞"],
  ["convention", "きまり", "kimari", "名詞"],
  ["coverage", "かばれっじ", "kabarejji", "名詞"],
  ["creation", "そうぞう", "souzou", "名詞"],
  ["criteria", "きじゅん", "kijun", "名詞"],
  ["damage", "そんがい", "songai", "名詞"],
  ["data", "でーた", "deeta", "名詞"],
  ["decrease", "げんしょう", "genshou", "名詞"],
  ["definition", "ていぎ", "teigi", "名詞"],
  ["demand", "じゅよう", "juyou", "名詞"],
  ["demonstration", "じっれい", "jitsurei", "名詞"],
  ["development", "かいはつ", "kaihatsu", "名詞"],
  ["difference", "ちがい", "chigai", "名詞"],
  ["difficulty", "こんなん", "konnan", "名詞"],
  ["effect", "こうか", "kouka", "名詞"],
  ["element", "ようそ", "youso", "名詞"],
  ["emphasis", "きょうちょう", "kyouchou", "名詞"],
  ["employment", "こよう", "koyou", "名詞"],
  ["energy", "えねるぎー", "enerugii", "名詞"],
  ["error", "えらー", "eraa", "名詞"],
  ["establishment", "せつりつ", "setsuritsu", "名詞"],
  ["evaluation", "ひょうか", "hyouka", "名詞"],
  ["event", "いべんと", "ibento", "名詞"],
  ["evidence", "しょうこ", "shouko", "名詞"],
  ["example", "れい", "rei", "名詞"],
  ["exception", "れいがい", "reigai", "名詞"],
  ["expansion", "かくだい", "kakudai", "名詞"],
  ["expectation", "きたい", "kitai", "名詞"],
  ["expert", "せんもんか", "senmonka", "名詞"],
  ["explanation", "せつめい", "setsumei", "名詞"],
  ["extent", "はんい", "han'i", "名詞"],
  ["failure", "しっぱい", "shippai", "名詞"],
  ["feature", "とくちょう", "tokuchou", "名詞"],
  ["fee", "りょうきん", "ryoukin", "名詞"],
  ["file", "ふぁいる", "fairu", "名詞"],
  ["finding", "はっけん", "hakken", "名詞"],
  ["flow", "ふろー", "furoo", "名詞"],
  ["fund", "ききん", "kikin", "名詞"],
  ["guideline", "がいどらいん", "gaidorain", "名詞"],
  ["handling", "とりあつかい", "toriatsukai", "名詞"],
  ["impact", "えいきょう", "eikyou", "名詞"],
  ["importance", "じゅうようせい", "juuyousei", "名詞"],
  ["improvement", "かいぜん", "kaizen", "名詞"],
  ["incentive", "しどうきん", "shidoukin", "名詞"],
  ["indication", "しめすこと", "shimesu koto", "名詞"],
  ["individual", "こじん", "kojin", "名詞"],
  ["influence", "えいきょう", "eikyou", "名詞"],
  ["initiative", "しゅどう", "shudou", "名詞"],
  ["input", "いんぷっと", "inputto", "名詞"],
  ["inspection", "けんさ", "kensa", "名詞"],
  ["instance", "れい", "rei", "名詞"],
  ["instruction", "しじ", "shiji", "名詞"],
  ["insurance", "ほけん", "hoken", "名詞"],
  ["integration", "せつごう", "setsugou", "名詞"],
  ["interaction", "そうごさよう", "sougo sayou", "名詞"],
  ["interest", "きょうみ", "kyoumi", "名詞"],
  ["introduction", "しょうかい", "shoukai", "名詞"],
  ["investment", "とうし", "toushi", "名詞"],
  ["issue", "もんだい", "mondai", "名詞"],
  ["job", "しごと", "shigoto", "名詞"],
  ["knowledge", "ちしき", "chishiki", "名詞"],
  ["lack", "けつぼう", "ketsubou", "名詞"],
  ["lead", "りーど", "riido", "名詞"],
  ["limit", "げんかい", "genkai", "名詞"],
  ["line", "らいん", "rain", "名詞"],
  ["list", "りすと", "risuto", "名詞"],
  ["loss", "そんしつ", "sonshitsu", "名詞"],
  ["maintenance", "ほぜん", "hozen", "名詞"],
  ["manner", "やりかた", "yarikata", "名詞"],
  ["material", "ざいりょう", "zairyou", "名詞"],
  ["matter", "もんだい", "mondai", "名詞"],
  ["means", "しゅだん", "shudan", "名詞"],
  ["measure", "そち", "sochi", "名詞"],
  ["member", "めんばー", "menbaa", "名詞"],
  ["method", "ほうほう", "houhou", "名詞"],
  ["minimum", "さいしょう", "saishou", "名詞"],
  ["mistake", "まちがい", "machigai", "名詞"],
  ["mode", "もーど", "moodo", "名詞"],
  ["model", "もでる", "moderu", "名詞"],
  ["need", "ひつよう", "hitsuyou", "名詞"],
  ["negotiation", "こうしょう", "koushou", "名詞"],
  ["network", "ねっとわーく", "nettowaaku", "名詞"],
  ["objective", "もくてき", "mokuteki", "名詞"],
  ["obligation", "ぎむ", "gimu", "名詞"],
  ["operation", "そうさ", "sousa", "名詞"],
  ["opportunity", "きかい", "kikai", "名詞"],
  ["option", "おぷしょん", "opushon", "名詞"],
  ["organization", "そしき", "soshiki", "名詞"],
  ["outcome", "けっか", "kekka", "名詞"],
  ["output", "あうとぷっと", "autoputto", "名詞"],
  ["part", "ぶぶん", "bubun", "名詞"],
  ["participant", "さんかしゃ", "sankasha", "名詞"],
  ["partnership", "ぱーとなーしっぷ", "paatonaashippu", "名詞"],
  ["percentage", "ぱーせんと", "paasento", "名詞"],
  ["period", "きかん", "kikan", "名詞"],
  ["permission", "きょか", "kyoka", "名詞"],
  ["portion", "ぶぶん", "bubun", "名詞"],
  ["position", "ちい", "chii", "名詞"],
  ["possibility", "かのうせい", "kanousei", "名詞"],
  ["practice", "れんしゅう", "renshuu", "名詞"],
  ["preparation", "じゅんび", "junbi", "名詞"],
  ["presence", "そんざい", "sonzai", "名詞"],
  ["presentation", "ぷれぜん", "purezen", "名詞"],
  ["pressure", "あつりょく", "atsuryoku", "名詞"],
  ["priority", "ゆうせん", "yuusen", "名詞"],
  ["procedure", "てつづき", "tetsuzuki", "名詞"],
  ["production", "せいさん", "seisan", "名詞"],
  ["profit", "りえき", "rieki", "名詞"],
  ["progress", "しんちょく", "shinchoku", "名詞"],
  ["promotion", "ぷろもーしょん", "puromooshon", "名詞"],
  ["proof", "しょうこ", "shouko", "名詞"],
  ["property", "しょゆうぶつ", "shoyuubutsu", "名詞"],
  ["proposal", "ていあん", "teian", "名詞"],
  ["protection", "ほご", "hogo", "名詞"],
  ["provision", "きょうきゅう", "kyoukyuu", "名詞"],
  ["purpose", "もくてき", "mokuteki", "名詞"],
  ["quality", "ひんしつ", "hinshitsu", "名詞"],
  ["quantity", "りょう", "ryou", "名詞"],
  ["question", "しつもん", "shitsumon", "名詞"],
  ["range", "はんい", "han'i", "名詞"],
  ["ratio", "ひりつ", "hiritsu", "名詞"],
  ["reason", "りゆう", "riyuu", "名詞"],
  ["recommendation", "すいせん", "suisen", "名詞"],
  ["record", "きろく", "kiroku", "名詞"],
  ["reference", "さんこう", "sankou", "名詞"],
  ["reflection", "はんせい", "hansei", "名詞"],
  ["relation", "かんけい", "kankei", "名詞"],
  ["relationship", "かんけい", "kankei", "名詞"],
  ["release", "りりーす", "ririisu", "名詞"],
  ["request", "ようせい", "yousei", "名詞"],
  ["requirement", "ようきゅう", "youkyuu", "名詞"],
  ["resource", "しげん", "shigen", "名詞"],
  ["response", "へんじ", "henji", "名詞"],
  ["responsibility", "せきにん", "sekinin", "名詞"],
  ["return", "かえり", "kaeri", "名詞"],
  ["review", "ふりかえり", "furikaeri", "名詞"],
  ["rule", "きまり", "kimari", "名詞"],
  ["safety", "あんぜん", "anzen", "名詞"],
  ["sale", "はんばい", "hanbai", "名詞"],
  ["sample", "さんぷる", "sanpuru", "名詞"],
  ["scale", "すけーる", "sukeeru", "名詞"],
  ["scope", "はんい", "han'i", "名詞"],
  ["section", "ぶもん", "bumon", "名詞"],
  ["sector", "せくたー", "sekutaa", "名詞"],
  ["selection", "せんたく", "sentaku", "名詞"],
  ["session", "せっしょん", "sesshon", "名詞"],
  ["setting", "せってい", "settei", "名詞"],
  ["share", "しぇあ", "shea", "名詞"],
  ["shift", "しふと", "shifuto", "名詞"],
  ["significance", "いぎ", "igi", "名詞"],
  ["situation", "じょうきょう", "joukyou", "名詞"],
  ["skill", "すきる", "sukiru", "名詞"],
  ["solution", "かいけつ", "kaiketsu", "名詞"],
  ["source", "みなもと", "minamoto", "名詞"],
  ["space", "くうかん", "kuukan", "名詞"],
  ["specification", "しよう", "shiyou", "名詞"],
  ["stage", "すてーじ", "suteeji", "名詞"],
  ["standard", "ひょうじゅん", "hyoujun", "名詞"],
  ["statement", "せつめい", "setsumei", "名詞"],
  ["status", "すてーたす", "suteetasu", "名詞"],
  ["step", "すてっぷ", "suteppu", "名詞"],
  ["stock", "ざいこ", "zaiko", "名詞"],
  ["storage", "ほぞん", "hozon", "名詞"],
  ["strategy", "せんりゃく", "senryaku", "名詞"],
  ["structure", "こうぞう", "kouzou", "名詞"],
  ["study", "けんきゅう", "kenkyuu", "名詞"],
  ["subject", "しゅだい", "shudai", "名詞"],
  ["success", "せいこう", "seikou", "名詞"],
  ["suggestion", "ていあん", "teian", "名詞"],
  ["target", "たーげっと", "taagetto", "名詞"],
  ["task", "たすく", "tasuku", "名詞"],
  ["team", "ちーむ", "chiimu", "名詞"],
  ["technique", "ぎじゅつ", "gijutsu", "名詞"],
  ["technology", "てくのろじー", "tekunorojii", "名詞"],
  ["term", "きかん", "kikan", "名詞"],
  ["theme", "てーま", "teema", "名詞"],
  ["topic", "とぴっく", "topikku", "名詞"],
  ["total", "ぜんたい", "zentai", "名詞"],
  ["trade", "ぼうえき", "boueki", "名詞"],
  ["transfer", "いてん", "iten", "名詞"],
  ["transition", "移行", "ikou", "名詞"],
  ["trend", "とれんど", "torendo", "名詞"],
  ["unit", "ゆにっと", "yunitto", "名詞"],
  ["variety", "たようせい", "tayousei", "名詞"],
  ["version", "ばーじょん", "baajon", "名詞"],
  ["view", "けんかい", "kenkai", "名詞"],
  ["volume", "ぼりゅーむ", "boryuumu", "名詞"],
  ["work", "しごと", "shigoto", "名詞"]
];

// 重複チェック: basicWordList 1-100 に含まれる en を除外した TSL 251-500 用
// vocabulary600 は既存100語 + 150語で250語。既存100語は wordList630 のまま。251-500の残り150語を追加。
const VOCAB600_EXTRA = [
  ["requirement", "ようきゅう", "youkyuu", "名詞"],
  ["reservation", "よやく", "yoyaku", "名詞"],
  ["retail", "こうり", "kouri", "名詞"],
  ["software", "そふとうぇあ", "sofutouea", "名詞"],
  ["subsidiary", "こがいしゃ", "kogaisha", "名詞"],
  ["supplier", "きょうきゅうしゃ", "kyoukyuusha", "名詞"],
  ["transaction", "とりひき", "torihiki", "名詞"],
  ["warehouse", "そうこ", "souko", "名詞"],
  ["warranty", "ほしょう", "hoshou", "名詞"],
  ["attendance", "しゅっせき", "shusseki", "名詞"],
  ["authorize", "けんきをあたえる", "kenki wo ataeru", "動詞"],
  ["automate", "じどうかする", "jidouka suru", "動詞"],
  ["compliance", "じゅんしゅ", "junshu", "名詞"],
  ["confidential", "きみつの", "kimitsu no", "形容詞"],
  ["consolidate", "とうごうする", "tougou suru", "動詞"],
  ["coordinate", "とりまとめる", "torimatomeru", "動詞"],
  ["delegate", "いにんする", "inin suru", "動詞"],
  ["demonstrate", "じっこうしてしめす", "jikkou shite shimesu", "動詞"],
  ["documentation", "しょるいか", "shorui ka", "名詞"],
  ["eligible", "しかくのある", "shikaku no aru", "形容詞"],
  ["establish", "せつりつする", "setsuritsu suru", "動詞"],
  ["expertise", "せんもんちしき", "senmon chishiki", "名詞"],
  ["facilitate", "じゅんちょうにする", "junchou ni suru", "動詞"],
  ["implement", "じっしする", "jisshi suru", "動詞"],
  ["incentive", "しどうきん", "shidoukin", "名詞"],
  ["infrastructure", "きそしせつ", "kiso shisetsu", "名詞"],
  ["innovative", "かくしんてきな", "kakushinteki na", "形容詞"],
  ["liaison", "れんらくやく", "renrakuyaku", "名詞"],
  ["mandatory", "ひっすの", "hissu no", "形容詞"],
  ["optimize", "さいてきかする", "saiteki ka suru", "動詞"],
  ["prioritize", "ゆうせんじゅんいをつける", "yuusen jun'i wo tsukeru", "動詞"],
  ["protocol", "ぎょうれつ", "gyouretsu", "名詞"],
  ["qualification", "しかく", "shikaku", "名詞"],
  ["redundant", "じゅうふくな", "juufuku na", "形容詞"],
  ["regulatory", "きせいの", "kisei no", "形容詞"],
  ["streamline", "こうりゅうかする", "kouryuuka suru", "動詞"],
  ["submit", "ていしゅつする", "teishutsu suru", "動詞"],
  ["terminate", "しゅうりょうする", "shuuryou suru", "動詞"],
  ["valid", "ゆうこうな", "yuukou na", "形容詞"],
  ["verify", "かくにんする", "kakunin suru", "動詞"],
  ["accommodate", "うけいれる", "ukeireru", "動詞"],
  ["acknowledge", "みとめる", "mitomeru", "動詞"],
  ["adjourn", "えんきする", "enki suru", "動詞"],
  ["allocate", "わりあてる", "wariateru", "動詞"],
  ["amend", "しゅうせいする", "shuusei suru", "動詞"],
  ["anticipate", "よそうする", "yosou suru", "動詞"],
  ["assemble", "あつめる", "atsumeru", "動詞"],
  ["assess", "ひょうかする", "hyouka suru", "動詞"],
  ["assist", "ほじょする", "hojo suru", "動詞"],
  ["assume", "かんがえる", "kangaeru", "動詞"],
  ["assure", "ほあんする", "hoan suru", "動詞"],
  ["audit", "かんさする", "kansa suru", "動詞"],
  ["avoid", "さける", "sakeru", "動詞"],
  ["clarify", "めいかくにする", "meikaku ni suru", "動詞"],
  ["collaborate", "きょうりょくする", "kyouryoku suru", "動詞"],
  ["commence", "かいしする", "kaishi suru", "動詞"],
  ["compensate", "ほしょうする", "hoshou suru", "動詞"],
  ["complement", "ほきょうする", "hokyou suru", "動詞"],
  ["comply", "したがう", "shitagau", "動詞"],
  ["convene", "しゅうごうする", "shuugou suru", "動詞"],
  ["convey", "つたえる", "tsutaeru", "動詞"],
  ["deduct", "さしひく", "sashihiku", "動詞"],
  ["defer", "えんきする", "enki suru", "動詞"],
  ["delete", "さくじょする", "sakujo suru", "動詞"],
  ["designate", "していする", "shitei suru", "動詞"],
  ["dispose", "しょりする", "shori suru", "動詞"],
  ["distinguish", "くべつする", "kubetsu suru", "動詞"],
  ["dominate", "しはいする", "shihai suru", "動詞"],
  ["eliminate", "のぞく", "nozoku", "動詞"],
  ["emphasize", "きょうちょうする", "kyouchou suru", "動詞"],
  ["enable", "可能にする", "kanou ni suru", "動詞"],
  ["enforce", "きょうせいする", "kyousei suru", "動詞"],
  ["engage", "かかわる", "kakawaru", "動詞"],
  ["enhance", "こうじょうする", "koujou suru", "動詞"],
  ["exceed", "こえる", "koeru", "動詞"],
  ["execute", "じっこうする", "jikkou suru", "動詞"],
  ["expedite", "すみやかにする", "sumiyaka ni suru", "動詞"],
  ["export", "ゆしゅつする", "yushutsu suru", "動詞"],
  ["extend", "のばす", "nobasu", "動詞"],
  ["finalize", "けっていする", "kettei suru", "動詞"],
  ["formalize", "かたちかする", "katachika suru", "動詞"],
  ["generate", "せいせいする", "seisei suru", "動詞"],
  ["grant", "じゅよする", "juyo suru", "動詞"],
  ["highlight", "ひょうめいする", "hyoumei suru", "動詞"],
  ["impose", "かすする", "kasu suru", "動詞"],
  ["incorporate", "とりこむ", "torikomu", "動詞"],
  ["indicate", "しめす", "shimesu", "動詞"],
  ["inform", "つたえる", "tsutaeru", "動詞"],
  ["initiate", "かいしする", "kaishi suru", "動詞"],
  ["insert", "そうにゅうする", "sounyuu suru", "動詞"],
  ["inspect", "けんさする", "kensa suru", "動詞"],
  ["install", "せつびする", "setsubi suru", "動詞"],
  ["integrate", "せつごうする", "setsugou suru", "動詞"],
  ["interpret", "かいしゃくする", "kaishaku suru", "動詞"],
  ["intervene", "かいにゅうする", "kainyuu suru", "動詞"],
  ["introduce", "しょうかいする", "shoukai suru", "動詞"],
  ["involve", "かかわる", "kakawaru", "動詞"],
  ["justify", "せいとうかする", "seitouka suru", "動詞"],
  ["launch", "ろーんちする", "roonchi suru", "動詞"],
  ["locate", "いちをさだめる", "ichi wo sadameru", "動詞"],
  ["maximize", "さいだいかする", "saidai ka suru", "動詞"],
  ["minimize", "さいしょうかする", "saishou ka suru", "動詞"],
  ["modify", "しゅうせいする", "shuusei suru", "動詞"],
  ["monitor", "かんしする", "kanshi suru", "動詞"],
  ["obtain", "える", "eru", "動詞"],
  ["operate", "うんえいする", "un'ei suru", "動詞"],
  ["organize", "そしきする", "soshiki suru", "動詞"],
  ["outline", "あらすじ", "arasuji", "名詞"],
  ["overcome", "こくふくする", "kokufuku suru", "動詞"],
  ["participate", "さんかする", "sanka suru", "動詞"],
  ["perform", "おこなう", "okonau", "動詞"],
  ["prepare", "じゅんびする", "junbi suru", "動詞"],
  ["present", "ていしゅつする", "teishutsu suru", "動詞"],
  ["prevent", "ふせぐ", "fusegu", "動詞"],
  ["produce", "せいさんする", "seisan suru", "動詞"],
  ["promote", "そうしんする", "soushin suru", "動詞"],
  ["provide", "ていきょうする", "teikyou suru", "動詞"],
  ["purchase", "こうにゅうする", "kounyuu suru", "動詞"],
  ["pursue", "ついきゅうする", "tsuikyuu suru", "動詞"],
  ["qualify", "しかくをえる", "shikaku wo eru", "動詞"],
  ["receive", "うけとる", "uketoru", "動詞"],
  ["recommend", "すいせんする", "suisen suru", "動詞"],
  ["reduce", "へらす", "herasu", "動詞"],
  ["refer", "さんしょうする", "sanshou suru", "動詞"],
  ["register", "とうろくする", "touroku suru", "動詞"],
  ["regulate", "きせいする", "kisei suru", "動詞"],
  ["reinforce", "きょうかする", "kyouka suru", "動詞"],
  ["reject", "きょぜつする", "kyozetsu suru", "動詞"],
  ["release", "りりーすする", "ririisu suru", "動詞"],
  ["remain", "のこる", "nokoru", "動詞"],
  ["remove", "とりのぞく", "torinozoku", "動詞"],
  ["replace", "おきかえる", "okikaeru", "動詞"],
  ["represent", "だいひょうする", "daihyou suru", "動詞"],
  ["resolve", "かいけつする", "kaiketsu suru", "動詞"],
  ["respond", "へんじする", "henji suru", "動詞"],
  ["restrict", "せいげんする", "seigen suru", "動詞"],
  ["retain", "ほじする", "hoji suru", "動詞"],
  ["revise", "しゅうせいする", "shuusei suru", "動詞"],
  ["select", "えらぶ", "erabu", "動詞"],
  ["separate", "ぶんりする", "bunri suru", "動詞"],
  ["settle", "けっさいする", "kessai suru", "動詞"],
  ["simplify", "かんりょうする", "kanryou suru", "動詞"],
  ["solve", "かいけつする", "kaiketsu suru", "動詞"],
  ["specify", "していする", "shitei suru", "動詞"],
  ["spend", "つかう", "tsukau", "動詞"],
  ["standardize", "ひょうじゅんかする", "hyoujunka suru", "動詞"],
  ["summarize", "ようやくする", "youyaku suru", "動詞"],
  ["supply", "きょうきゅうする", "kyoukyuu suru", "動詞"],
  ["train", "くんれんする", "kunren suru", "動詞"],
  ["transform", "へんかんする", "henkan suru", "動詞"],
  ["translate", "ほんやくする", "hon'yaku suru", "動詞"],
  ["transport", "ゆそうする", "yusou suru", "動詞"],
  ["update", "こうしんする", "koushin suru", "動詞"],
  ["utilize", "りようする", "riyou suru", "動詞"],
  ["withdraw", "ひきあげる", "hikiageru", "動詞"]
];

function entry(no, en, ja, romaji, pos) {
  return `    { no: ${no}, en: "${en}", ja: "${ja}", romaji: "${romaji}", pos: "${pos}" }`;
}

function formatBasicExtra() {
  return BASIC_EXTRA.map((row, i) => entry(101 + i, row[0], row[1], row[2], row[3])).join(",\n");
}

function formatVocab600Extra() {
  return VOCAB600_EXTRA.map((row, i) => entry(101 + i, row[0], row[1], row[2], row[3])).join(",\n");
}

module.exports = { BASIC_EXTRA, VOCAB600_EXTRA };

if (require.main === module) {
  const dir = __dirname;
  let wordListJs = fs.readFileSync(path.join(dir, "wordList.js"), "utf8");
  let wordList630Js = fs.readFileSync(path.join(dir, "wordList630.js"), "utf8");
  const basicMatch = wordListJs.match(/const basicWordList = \[([\s\S]*?)\n\];/);
  if (basicMatch) {
    const basicNew = "// 頻出トップ250用単語リスト - TSL ランク 1-250\nconst basicWordList = [\n" + basicMatch[1].trim() + ",\n" + formatBasicExtra() + "\n];";
    wordListJs = wordListJs.replace(/\/\/ 頻出トップ100用[\s\S]*?const basicWordList = \[[\s\S]*?\n\];/, basicNew);
  }
  const vocab630Match = wordList630Js.match(/const vocabulary600 = \[([\s\S]*?)\n\];/);
  if (vocab630Match) {
    const vocab630New = `// Level 2（目標600点レベル）用単語リスト - 250語（TSL 251-500）
const vocabulary600 = [
` + vocab630Match[1].trim() + ",\n" + formatVocab600Extra() + "\n];";
    wordList630Js = wordList630Js.replace(/\/\/ Level 2[\s\S]*?const vocabulary600 = \[[\s\S]*?\n\];/, vocab630New);
  }
  fs.writeFileSync(path.join(dir, "wordList.js"), wordListJs);
  fs.writeFileSync(path.join(dir, "wordList630.js"), wordList630Js);
  console.log("Done: basicWordList, vocabulary600 -> 250 words each");
}
