const newWordList = [
    { no: 1, en: "abolish", ja: "はいしする", romaji: "haishi suru", pos: "動詞" },
    { no: 2, en: "absorb", ja: "きゅうしゅうする", romaji: "kyuushuu suru", pos: "動詞" },
    { no: 3, en: "abstract", ja: "ちゅうしょうてきな", romaji: "chuushouteki na", pos: "形容詞" },
    { no: 4, en: "accelerate", ja: "かそくする", romaji: "kasoku suru", pos: "動詞" },
    { no: 5, en: "accommodate", ja: "うけいれる", romaji: "ukeireru", pos: "動詞" },
    { no: 6, en: "accompany", ja: "つれそう", romaji: "tsuresou", pos: "動詞" },
    { no: 7, en: "accomplish", ja: "なしとげる", romaji: "nashitogeru", pos: "動詞" },
    { no: 8, en: "acknowledge", ja: "みとめる", romaji: "mitomeru", pos: "動詞" },
    { no: 9, en: "acquire", ja: "えたえる", romaji: "etaeru", pos: "動詞" },
    { no: 10, en: "adapt", ja: "てきおうする", romaji: "tekiou suru", pos: "動詞" },
    { no: 11, en: "adhere", ja: "したがう", romaji: "shitagau", pos: "動詞" },
    { no: 12, en: "adjust", ja: "ちょうせいする", romaji: "chousei suru", pos: "動詞" },
    { no: 13, en: "administer", ja: "かんりする", romaji: "kanri suru", pos: "動詞" },
    { no: 14, en: "advocate", ja: "となえる", romaji: "tonaeru", pos: "動詞" },
    { no: 15, en: "affect", ja: "えいきょうする", romaji: "eikyou suru", pos: "動詞" },
    { no: 16, en: "affiliate", ja: "しゅうせきする", romaji: "shuuseki suru", pos: "動詞" },
    { no: 17, en: "afford", ja: "よゆうがある", romaji: "yoyuu ga aru", pos: "動詞" },
    { no: 18, en: "aggregate", ja: "しゅうごうする", romaji: "shuugou suru", pos: "動詞" },
    { no: 19, en: "allocate", ja: "わりあてる", romaji: "wariateru", pos: "動詞" },
    { no: 20, en: "amend", ja: "しゅうせいする", romaji: "shuusei suru", pos: "動詞" },
    { no: 21, en: "analogy", ja: "るいれい", romaji: "ruirei", pos: "名詞" },
    { no: 22, en: "analyze", ja: "ぶんせきする", romaji: "bunseki suru", pos: "動詞" },
    { no: 23, en: "announce", ja: "せいめいする", romaji: "seimei suru", pos: "動詞" },
    { no: 24, en: "apparent", ja: "めいらかな", romaji: "meiraka na", pos: "形容詞" },
    { no: 25, en: "appoint", ja: "にんめいする", romaji: "ninmei suru", pos: "動詞" },
    { no: 26, en: "appraise", ja: "ひょうかする", romaji: "hyouka suru", pos: "動詞" },
    { no: 27, en: "approximate", ja: "およその", romaji: "oyoso no", pos: "形容詞" },
    { no: 28, en: "arbitrary", ja: "きまぐれな", romaji: "kimagure na", pos: "形容詞" },
    { no: 29, en: "articulate", ja: "めいりょうにのべる", romaji: "meiryou ni noberu", pos: "動詞" },
    { no: 30, en: "ascertain", ja: "かくにんする", romaji: "kakunin suru", pos: "動詞" },
    { no: 31, en: "assemble", ja: "あつめる", romaji: "atsumeru", pos: "動詞" },
    { no: 32, en: "assess", ja: "ひょうかする", romaji: "hyouka suru", pos: "動詞" },
    { no: 33, en: "assure", ja: "ほあんする", romaji: "hoan suru", pos: "動詞" },
    { no: 34, en: "attain", ja: "たっする", romaji: "tassuru", pos: "動詞" },
    { no: 35, en: "attribute", ja: "きせいする", romaji: "kisei suru", pos: "動詞" },
    { no: 36, en: "auxiliary", ja: "ほじょの", romaji: "hojo no", pos: "形容詞" },
    { no: 37, en: "avail", ja: "りようする", romaji: "riyou suru", pos: "動詞" },
    { no: 38, en: "avert", ja: "さける", romaji: "sakeru", pos: "動詞" },
    { no: 39, en: "award", ja: "じゅしょう", romaji: "jushou", pos: "名詞" },
    { no: 40, en: "barrier", ja: "しょうがい", romaji: "shougai", pos: "名詞" },
    { no: 41, en: "baseline", ja: "きじゅんせん", romaji: "kijunsen", pos: "名詞" },
    { no: 42, en: "bear", ja: "おう", romaji: "ou", pos: "動詞" },
    { no: 43, en: "behalf", ja: "ために", romaji: "tame ni", pos: "名詞" },
    { no: 44, en: "benchmark", ja: "ひょうじゅん", romaji: "hyoujun", pos: "名詞" },
    { no: 45, en: "bind", ja: "しばる", romaji: "shibaru", pos: "動詞" },
    { no: 46, en: "bond", ja: "きんこう", romaji: "kinkou", pos: "名詞" },
    { no: 47, en: "bonus", ja: "ぼーなす", romaji: "boonasu", pos: "名詞" },
    { no: 48, en: "boost", ja: "つよめる", romaji: "tsuyomeru", pos: "動詞" },
    { no: 49, en: "border", ja: "きょうかい", romaji: "kyoukai", pos: "名詞" },
    { no: 50, en: "borrow", ja: "かりる", romaji: "kariru", pos: "動詞" },
    { no: 51, en: "bound", ja: "けいやく", romaji: "keiyaku", pos: "名詞" },
    { no: 52, en: "breach", ja: "いはん", romaji: "ihan", pos: "名詞" },
    { no: 53, en: "broadcast", ja: "ほうそうする", romaji: "housou suru", pos: "動詞" },
    { no: 54, en: "bulk", ja: "かさ", romaji: "kasa", pos: "名詞" },
    { no: 55, en: "burden", ja: "ふたん", romaji: "futan", pos: "名詞" },
    { no: 56, en: "bypass", ja: "ばいぱす", romaji: "baipasu", pos: "名詞" },
    { no: 57, en: "cable", ja: "けーぶる", romaji: "keeburu", pos: "名詞" },
    { no: 58, en: "calculate", ja: "けいさんする", romaji: "keisan suru", pos: "動詞" },
    { no: 59, en: "cancel", ja: "とりけす", romaji: "torikesu", pos: "動詞" },
    { no: 60, en: "capability", ja: "のうりょく", romaji: "nouryoku", pos: "名詞" },
    { no: 61, en: "capture", ja: "ほかくする", romaji: "hokaku suru", pos: "動詞" },
    { no: 62, en: "carry", ja: "はこぶ", romaji: "hakobu", pos: "動詞" },
    { no: 63, en: "cast", ja: "とうひょう", romaji: "touhyou", pos: "名詞" },
    { no: 64, en: "catalog", ja: "かたろぐ", romaji: "katarogu", pos: "名詞" },
    { no: 65, en: "category", ja: "ぶるい", romaji: "burui", pos: "名詞" },
    { no: 66, en: "cease", ja: "やめる", romaji: "yameru", pos: "動詞" },
    { no: 67, en: "central", ja: "ちゅうおうの", romaji: "chuuo no", pos: "形容詞" },
    { no: 68, en: "certificate", ja: "しょうめいしょ", romaji: "shoumeisho", pos: "名詞" },
    { no: 69, en: "challenge", ja: "ちょうせん", romaji: "chousen", pos: "名詞" },
    { no: 70, en: "channel", ja: "ちゃんねる", romaji: "channeru", pos: "名詞" },
    { no: 71, en: "character", ja: "せいかく", romaji: "seikaku", pos: "名詞" },
    { no: 72, en: "chart", ja: "ずひょう", romaji: "zuhyou", pos: "名詞" },
    { no: 73, en: "chase", ja: "おいかける", romaji: "oikakeru", pos: "動詞" },
    { no: 74, en: "cite", ja: "いんようする", romaji: "in'you suru", pos: "動詞" },
    { no: 75, en: "clause", ja: "こうかん", romaji: "koukan", pos: "名詞" },
    { no: 76, en: "clear", ja: "めいりょうな", romaji: "meiryou na", pos: "形容詞" },
    { no: 77, en: "climate", ja: "ふんいき", romaji: "funiki", pos: "名詞" },
    { no: 78, en: "collapse", ja: "ほうかいする", romaji: "houkai suru", pos: "動詞" },
    { no: 79, en: "collect", ja: "あつめる", romaji: "atsumeru", pos: "動詞" },
    { no: 80, en: "compact", ja: "こんぱくとな", romaji: "konpakuto na", pos: "形容詞" },
    { no: 81, en: "complement", ja: "ほきょうする", romaji: "hokyou suru", pos: "動詞" },
    { no: 82, en: "compose", ja: "そうせいする", romaji: "sousei suru", pos: "動詞" },
    { no: 83, en: "comprehensive", ja: "そうごうてきな", romaji: "sougouteki na", pos: "形容詞" },
    { no: 84, en: "comprise", ja: "ふくむ", romaji: "fukumu", pos: "動詞" },
    { no: 85, en: "compromise", ja: "だきょうする", romaji: "dakyou suru", pos: "動詞" },
    { no: 86, en: "compute", ja: "けいさんする", romaji: "keisan suru", pos: "動詞" },
    { no: 87, en: "conceive", ja: "かんがえだす", romaji: "kangaedasu", pos: "動詞" },
    { no: 88, en: "concentrate", ja: "しゅうちゅうする", romaji: "chuuchuu suru", pos: "動詞" },
    { no: 89, en: "confer", ja: "あたえる", romaji: "ataeru", pos: "動詞" },
    { no: 90, en: "confine", ja: "かぎる", romaji: "kagiru", pos: "動詞" },
    { no: 91, en: "conform", ja: "したがう", romaji: "shitagau", pos: "動詞" },
    { no: 92, en: "constitute", ja: "こうせいする", romaji: "kousei suru", pos: "動詞" },
    { no: 93, en: "constrain", ja: "せいげんする", romaji: "seigen suru", pos: "動詞" },
    { no: 94, en: "construct", ja: "けんせつする", romaji: "kensetsu suru", pos: "動詞" },
    { no: 95, en: "consult", ja: "そうだんする", romaji: "soudan suru", pos: "動詞" },
    { no: 96, en: "consume", ja: "しょうひする", romaji: "shouhi suru", pos: "動詞" },
    { no: 97, en: "contend", ja: "あらそう", romaji: "arasou", pos: "動詞" },
    { no: 98, en: "contradict", ja: "むじゅんする", romaji: "mujun suru", pos: "動詞" },
    { no: 99, en: "convene", ja: "しゅうごうする", romaji: "shuugou suru", pos: "動詞" },
    { no: 100, en: "convince", ja: "なっとくさせる", romaji: "nattoku saseru", pos: "動詞" },
    { no: 101, en: "core", ja: "かく", romaji: "kaku", pos: "名詞" },
    { no: 102, en: "correct", ja: "ただしい", romaji: "tadashii", pos: "形容詞" },
    { no: 103, en: "counsel", ja: "じょげんする", romaji: "jogen suru", pos: "動詞" },
    { no: 104, en: "crucial", ja: "じゅうような", romaji: "juuyou na", pos: "形容詞" },
    { no: 105, en: "currency", ja: "つうか", romaji: "tsuuka", pos: "名詞" },
    { no: 106, en: "curve", ja: "きょくせん", romaji: "kyokussen", pos: "名詞" },
    { no: 107, en: "cycle", ja: "さいくる", romaji: "saikuru", pos: "名詞" },
    { no: 108, en: "defect", ja: "けってん", romaji: "ketten", pos: "名詞" },
    { no: 109, en: "defend", ja: "まもる", romaji: "mamoru", pos: "動詞" },
    { no: 110, en: "define", ja: "ていぎする", romaji: "teigi suru", pos: "動詞" },
    { no: 111, en: "delete", ja: "さくじょする", romaji: "sakujo suru", pos: "動詞" },
    { no: 112, en: "deliberate", ja: "しんしゃくする", romaji: "shinshaku suru", pos: "動詞" },
    { no: 113, en: "denote", ja: "しめす", romaji: "shimesu", pos: "動詞" },
    { no: 114, en: "deny", ja: "ひていする", romaji: "hitei suru", pos: "動詞" },
    { no: 115, en: "depart", ja: "しゅっぱつする", romaji: "shuppatsu suru", pos: "動詞" },
    { no: 116, en: "deposit", ja: "よきんする", romaji: "yokin suru", pos: "動詞" },
    { no: 117, en: "derive", ja: "えだす", romaji: "edasu", pos: "動詞" },
    { no: 118, en: "describe", ja: "きじゅつする", romaji: "kijutsu suru", pos: "動詞" },
    { no: 119, en: "designate", ja: "していする", romaji: "shitei suru", pos: "動詞" },
    { no: 120, en: "desire", ja: "のぞむ", romaji: "nozomu", pos: "動詞" },
    { no: 121, en: "detect", ja: "けんしゅつする", romaji: "kenshutsu suru", pos: "動詞" },
    { no: 122, en: "determine", ja: "きめる", romaji: "kimeru", pos: "動詞" },
    { no: 123, en: "device", ja: "そうち", romaji: "souchi", pos: "名詞" },
    { no: 124, en: "devote", ja: "ささげる", romaji: "sasageru", pos: "動詞" },
    { no: 125, en: "differ", ja: "ことなる", romaji: "kotonaru", pos: "動詞" },
    { no: 126, en: "dimension", ja: "じげん", romaji: "jigen", pos: "名詞" },
    { no: 127, en: "diminish", ja: "へらす", romaji: "herasu", pos: "動詞" },
    { no: 128, en: "disable", ja: "むのうにする", romaji: "munou ni suru", pos: "動詞" },
    { no: 129, en: "disagree", ja: "いこうする", romaji: "ikou suru", pos: "動詞" },
    { no: 130, en: "disclose", ja: "あきらかにする", romaji: "akiraka ni suru", pos: "動詞" },
    { no: 131, en: "discriminate", ja: "くべつする", romaji: "kubetsu suru", pos: "動詞" },
    { no: 132, en: "dismiss", ja: "かいこする", romaji: "kaiko suru", pos: "動詞" },
    { no: 133, en: "dispose", ja: "しょりする", romaji: "shori suru", pos: "動詞" },
    { no: 134, en: "dispute", ja: "ぎろん", romaji: "giron", pos: "名詞" },
    { no: 135, en: "distinct", ja: "めいりょうな", romaji: "meiryou na", pos: "形容詞" },
    { no: 136, en: "distinguish", ja: "くべつする", romaji: "kubetsu suru", pos: "動詞" },
    { no: 137, en: "diverse", ja: "たような", romaji: "tayou na", pos: "形容詞" },
    { no: 138, en: "dominate", ja: "しはいする", romaji: "shihai suru", pos: "動詞" },
    { no: 139, en: "duration", ja: "きかん", romaji: "kikan", pos: "名詞" },
    { no: 140, en: "dynamic", ja: "どうてきな", romaji: "douteki na", pos: "形容詞" },
    { no: 141, en: "earn", ja: "かせぐ", romaji: "kasegu", pos: "動詞" },
    { no: 142, en: "edit", ja: "へんしゅうする", romaji: "henshuu suru", pos: "動詞" },
    { no: 143, en: "eliminate", ja: "のぞく", romaji: "nozoku", pos: "動詞" },
    { no: 144, en: "emerge", ja: "あらわれる", romaji: "arawareru", pos: "動詞" },
    { no: 145, en: "emphasis", ja: "きょうちょう", romaji: "kyouchou", pos: "名詞" },
    { no: 146, en: "employ", ja: "こようする", romaji: "koyou suru", pos: "動詞" },
    { no: 147, en: "enact", ja: "せいていする", romaji: "seitei suru", pos: "動詞" },
    { no: 148, en: "encounter", ja: "であう", romaji: "deau", pos: "動詞" },
    { no: 149, en: "enforce", ja: "きょうせいする", romaji: "kyousei suru", pos: "動詞" },
    { no: 150, en: "entitle", ja: "けんりをあたえる", romaji: "kenri wo ataeru", pos: "動詞" },
    { no: 151, en: "equivalent", ja: "とうどうの", romaji: "toudou no", pos: "形容詞" },
    { no: 152, en: "essential", ja: "ひつような", romaji: "hitsuyou na", pos: "形容詞" },
    { no: 153, en: "ethic", ja: "りんり", romaji: "rinri", pos: "名詞" },
    { no: 154, en: "evolve", ja: "しんかする", romaji: "shinka suru", pos: "動詞" },
    { no: 155, en: "exempt", ja: "めんじょする", romaji: "menjo suru", pos: "動詞" },
    { no: 156, en: "expend", ja: "ついやす", romaji: "tsuiyasu", pos: "動詞" },
    { no: 157, en: "explicit", ja: "めいかくな", romaji: "meikaku na", pos: "形容詞" },
    { no: 158, en: "exploit", ja: "りようする", romaji: "riyou suru", pos: "動詞" },
    { no: 159, en: "export", ja: "ゆしゅつする", romaji: "yushutsu suru", pos: "動詞" },
    { no: 160, en: "expose", ja: "さらす", romaji: "sarasu", pos: "動詞" },
    { no: 161, en: "facilitate", ja: "じゅんちょうにする", romaji: "junchou ni suru", pos: "動詞" },
    { no: 162, en: "finite", ja: "ゆうげんな", romaji: "yuugen na", pos: "形容詞" },
    { no: 163, en: "flexible", ja: "じゅうなんな", romaji: "juunan na", pos: "形容詞" },
    { no: 164, en: "fulfill", ja: "じっげんする", romaji: "jissen suru", pos: "動詞" },
    { no: 165, en: "furnish", ja: "そなえる", romaji: "sonaeru", pos: "動詞" },
    { no: 166, en: "further", ja: "さらに", romaji: "sara ni", pos: "副詞" },
    { no: 167, en: "gap", ja: "ぎゃっぷ", romaji: "gyappu", pos: "名詞" },
    { no: 168, en: "generate", ja: "せいせいする", romaji: "seisei suru", pos: "動詞" },
    { no: 169, en: "global", ja: "ぐろーばるな", romaji: "guroobaruna", pos: "形容詞" },
    { no: 170, en: "govern", ja: "とりしまる", romaji: "torishimaru", pos: "動詞" },
    { no: 171, en: "heading", ja: "みだし", romaji: "midashi", pos: "名詞" },
    { no: 172, en: "hypothesis", ja: "かせつ", romaji: "kasetsu", pos: "名詞" },
    { no: 173, en: "illustrate", ja: "せつめいする", romaji: "setsumei suru", pos: "動詞" },
    { no: 174, en: "inherit", ja: "けいしょうする", romaji: "keishou suru", pos: "動詞" },
    { no: 175, en: "innovate", ja: "かくしんする", romaji: "kakushin suru", pos: "動詞" },
    { no: 176, en: "integral", ja: "ひつような", romaji: "hitsuyou na", pos: "形容詞" },
    { no: 177, en: "integrity", ja: "せいじゅん", romaji: "seijun", pos: "名詞" },
    { no: 178, en: "interval", ja: "かんかく", romaji: "kankaku", pos: "名詞" },
    { no: 179, en: "intrinsic", ja: "ほんらいの", romaji: "honrai no", pos: "形容詞" },
    { no: 180, en: "invoke", ja: "ひきだす", romaji: "hikidasu", pos: "動詞" },
    { no: 181, en: "isolate", ja: "こりつさせる", romaji: "koritsu saseru", pos: "動詞" },
    { no: 182, en: "layer", ja: "そう", romaji: "sou", pos: "名詞" },
    { no: 183, en: "legal", ja: "ほうりつてきな", romaji: "houritsuteki na", pos: "形容詞" },
    { no: 184, en: "legislate", ja: "りっぽうする", romaji: "rippou suru", pos: "動詞" },
    { no: 185, en: "levy", ja: "かぜいする", romaji: "kazei suru", pos: "動詞" },
    { no: 186, en: "liability", ja: "せきにん", romaji: "sekinin", pos: "名詞" },
    { no: 187, en: "logic", ja: "ろんり", romaji: "ronri", pos: "名詞" },
    { no: 188, en: "mandate", ja: "めんていする", romaji: "mentei suru", pos: "動詞" },
    { no: 189, en: "mature", ja: "せいじゅくする", romaji: "seijuku suru", pos: "動詞" },
    { no: 190, en: "maximize", ja: "さいだいかする", romaji: "saidai ka suru", pos: "動詞" },
    { no: 191, en: "mediate", ja: "ちゅうかいする", romaji: "chuukai suru", pos: "動詞" },
    { no: 192, en: "medium", ja: "ばい", romaji: "bai", pos: "名詞" },
    { no: 193, en: "mention", ja: "言及する", romaji: "genkyuu suru", pos: "動詞" },
    { no: 194, en: "merge", ja: "がっぺいする", romaji: "gappei suru", pos: "動詞" },
    { no: 195, en: "motive", ja: "どうき", romaji: "douki", pos: "名詞" },
    { no: 196, en: "nominate", ja: "ていめいする", romaji: "teimei suru", pos: "動詞" },
    { no: 197, en: "norm", ja: "きじゅん", romaji: "kijun", pos: "名詞" },
    { no: 198, en: "oblige", ja: "きょうせいする", romaji: "kyousei suru", pos: "動詞" },
    { no: 199, en: "occupy", ja: "せんきょする", romaji: "senkyo suru", pos: "動詞" },
    { no: 200, en: "occur", ja: "おこる", romaji: "okoru", pos: "動詞" },
    { no: 201, en: "offset", ja: "おふせっと", romaji: "ofusetto", pos: "名詞" },
    { no: 202, en: "organ", ja: "きかん", romaji: "kikan", pos: "名詞" },
    { no: 203, en: "orient", ja: "むける", romaji: "mukeru", pos: "動詞" },
    { no: 204, en: "overall", ja: "ぜんたいの", romaji: "zentai no", pos: "形容詞" },
    { no: 205, en: "overlap", ja: "ちょうふく", romaji: "choufuku", pos: "名詞" },
    { no: 206, en: "pace", ja: "ぺーす", romaji: "peesu", pos: "名詞" },
    { no: 207, en: "package", ja: "ぱっけーじ", romaji: "pakkeiji", pos: "名詞" },
    { no: 208, en: "panel", ja: "ぱねる", romaji: "paneru", pos: "名詞" },
    { no: 209, en: "parallel", ja: "へいこうの", romaji: "heikou no", pos: "形容詞" },
    { no: 210, en: "parameter", ja: "ぱらめーた", romaji: "parameta", pos: "名詞" },
    { no: 211, en: "patent", ja: "とっきょ", romaji: "tokkyo", pos: "名詞" },
    { no: 212, en: "pattern", ja: "ぱたーん", romaji: "pataan", pos: "名詞" },
    { no: 213, en: "pause", ja: "いちじていし", romaji: "ichiji teishi", pos: "名詞" },
    { no: 214, en: "peak", ja: "ちょうてん", romaji: "chouten", pos: "名詞" },
    { no: 215, en: "penalize", ja: "ばっする", romaji: "bassuru", pos: "動詞" },
    { no: 216, en: "perceive", ja: "ちかくする", romaji: "chikaku suru", pos: "動詞" },
    { no: 217, en: "perfect", ja: "かんぺきな", romaji: "kanpeki na", pos: "形容詞" },
    { no: 218, en: "perform", ja: "おこなう", romaji: "okonau", pos: "動詞" },
    { no: 219, en: "permit", ja: "ゆるす", romaji: "yurusu", pos: "動詞" },
    { no: 220, en: "persist", ja: "しつづける", romaji: "shitsuzukeru", pos: "動詞" },
    { no: 221, en: "phase", ja: "だんかい", romaji: "dankai", pos: "名詞" },
    { no: 222, en: "place", ja: "おく", romaji: "oku", pos: "動詞" },
    { no: 223, en: "plus", ja: "ぷらす", romaji: "purasu", pos: "名詞" },
    { no: 224, en: "point", ja: "てん", romaji: "ten", pos: "名詞" },
    { no: 225, en: "portion", ja: "ぶぶん", romaji: "bubun", pos: "名詞" },
    { no: 226, en: "pose", ja: "もたらす", romaji: "motarasu", pos: "動詞" },
    { no: 227, en: "positive", ja: "せいめいてきな", romaji: "seimeiteki na", pos: "形容詞" },
    { no: 228, en: "possess", ja: "もつ", romaji: "motsu", pos: "動詞" },
    { no: 229, en: "postpone", ja: "えんきする", romaji: "enki suru", pos: "動詞" },
    { no: 230, en: "potential", ja: "かのうせい", romaji: "kanousei", pos: "名詞" },
    { no: 231, en: "precede", ja: "さきだつ", romaji: "sakidatsu", pos: "動詞" },
    { no: 232, en: "precise", ja: "せいみつな", romaji: "seimitsu na", pos: "形容詞" },
    { no: 233, en: "predict", ja: "よそくする", romaji: "yosoku suru", pos: "動詞" },
    { no: 234, en: "prefer", ja: "このむ", romaji: "konomu", pos: "動詞" },
    { no: 235, en: "prescribe", ja: "しほうする", romaji: "shihou suru", pos: "動詞" },
    { no: 236, en: "preserve", ja: "ほぞんする", romaji: "hozon suru", pos: "動詞" },
    { no: 237, en: "press", ja: "おす", romaji: "osu", pos: "動詞" },
    { no: 238, en: "prevent", ja: "ふせぐ", romaji: "fusegu", pos: "動詞" },
    { no: 239, en: "prime", ja: "しゅような", romaji: "shuyou na", pos: "形容詞" },
    { no: 240, en: "principal", ja: "しゅような", romaji: "shuyou na", pos: "形容詞" },
    { no: 241, en: "principle", ja: "げんそく", romaji: "gensoku", pos: "名詞" },
    { no: 242, en: "prior", ja: "さきの", romaji: "saki no", pos: "形容詞" },
    { no: 243, en: "privilege", ja: "とくけん", romaji: "tokuken", pos: "名詞" },
    { no: 244, en: "proceed", ja: "つづける", romaji: "tsuzukeru", pos: "動詞" },
    { no: 245, en: "profile", ja: "ぷろふぃーる", romaji: "purofiiru", pos: "名詞" },
    { no: 246, en: "proportion", ja: "ひれい", romaji: "hirei", pos: "名詞" },
    { no: 247, en: "prospect", ja: "みこみ", romaji: "mikomi", pos: "名詞" },
    { no: 248, en: "protect", ja: "ほごする", romaji: "hogo suru", pos: "動詞" },
    { no: 249, en: "protocol", ja: "ぎょうれつ", romaji: "gyouretsu", pos: "名詞" },
    { no: 250, en: "publish", ja: "はっぴょうする", romaji: "happyou suru", pos: "動詞" }
];

const wordList860 = [
    { no: 1, en: "accomplishment", ja: "せいせき", romaji: "seiseki", pos: "名詞" },
    { no: 2, en: "administrative", ja: "ぎょうむの", romaji: "gyoumu no", pos: "形容詞" },
    { no: 3, en: "authorize", ja: "けんきをあたえる", romaji: "kenki wo ataeru", pos: "動詞" },
    { no: 4, en: "automate", ja: "じどうかする", romaji: "jidouka suru", pos: "動詞" },
    { no: 5, en: "compliance", ja: "じゅんしゅ", romaji: "junshu", pos: "名詞" },
    { no: 6, en: "confidential", ja: "きみつの", romaji: "kimitsu no", pos: "形容詞" },
    { no: 7, en: "consolidate", ja: "とうごうする", romaji: "tougou suru", pos: "動詞" },
    { no: 8, en: "coordinate", ja: "とりまとめる", romaji: "torimatomeru", pos: "動詞" },
    { no: 9, en: "delegate", ja: "いにんする", romaji: "inin suru", pos: "動詞" },
    { no: 10, en: "demonstrate", ja: "じっこうしてしめす", romaji: "jikkou shite shimesu", pos: "動詞" },
    { no: 11, en: "documentation", ja: "しょるいか", romaji: "shorui ka", pos: "名詞" },
    { no: 12, en: "eligible", ja: "しかくのある", romaji: "shikaku no aru", pos: "形容詞" },
    { no: 13, en: "establish", ja: "せつりつする", romaji: "setsuritsu suru", pos: "動詞" },
    { no: 14, en: "expertise", ja: "せんもんちしき", romaji: "senmon chishiki", pos: "名詞" },
    { no: 15, en: "formalize", ja: "けいしきかする", romaji: "keishikika suru", pos: "動詞" },
    { no: 16, en: "implement", ja: "じっしする", romaji: "jisshi suru", pos: "動詞" },
    { no: 17, en: "incentive", ja: "しどうきん", romaji: "shidoukin", pos: "名詞" },
    { no: 18, en: "infrastructure", ja: "きそしせつ", romaji: "kiso shisetsu", pos: "名詞" },
    { no: 19, en: "innovative", ja: "かくしんてきな", romaji: "kakushinteki na", pos: "形容詞" },
    { no: 20, en: "liaison", ja: "れんらくやく", romaji: "renrakuyaku", pos: "名詞" },
    { no: 21, en: "maintenance", ja: "ほぜん", romaji: "hozen", pos: "名詞" },
    { no: 22, en: "mandatory", ja: "ひっすの", romaji: "hissu no", pos: "形容詞" },
    { no: 23, en: "optimize", ja: "さいてきかする", romaji: "saiteki ka suru", pos: "動詞" },
    { no: 24, en: "prioritize", ja: "ゆうせんじゅんいをつける", romaji: "yuusen jun'i wo tsukeru", pos: "動詞" },
    { no: 25, en: "procedural", ja: "てつづきの", romaji: "tetsuzuki no", pos: "形容詞" },
    { no: 26, en: "qualification", ja: "しかく", romaji: "shikaku", pos: "名詞" },
    { no: 27, en: "redundant", ja: "じゅうふくな", romaji: "juufuku na", pos: "形容詞" },
    { no: 28, en: "regulatory", ja: "きせいの", romaji: "kisei no", pos: "形容詞" },
    { no: 29, en: "streamline", ja: "こうりゅうかする", romaji: "kouryuuka suru", pos: "動詞" },
    { no: 30, en: "supervisor", ja: "かんとくしゃ", romaji: "kantokusha", pos: "名詞" },
    { no: 31, en: "acquisition", ja: "かくとく", romaji: "kakutoku", pos: "名詞" },
    { no: 32, en: "arbitration", ja: "ちゅうさい", romaji: "chuusai", pos: "名詞" },
    { no: 33, en: "benchmarking", ja: "べんちまーきんぐ", romaji: "benchimakingu", pos: "名詞" },
    { no: 34, en: "bottleneck", ja: "ぼるねっく", romaji: "borunekku", pos: "名詞" },
    { no: 35, en: "breakthrough", ja: "だいほっとす", romaji: "daihottosu", pos: "名詞" },
    { no: 36, en: "consensus", ja: "ごうい", romaji: "goui", pos: "名詞" },
    { no: 37, en: "contingency", ja: "よき", romaji: "yoki", pos: "名詞" },
    { no: 38, en: "cost-effective", ja: "こすとこうかがたかい", romaji: "kosuto kouka ga takai", pos: "形容詞" },
    { no: 39, en: "counterpart", ja: "たいおうしゃ", romaji: "taiousha", pos: "名詞" },
    { no: 40, en: "deadline", ja: "しめきり", romaji: "shimekiri", pos: "名詞" },
    { no: 41, en: "discrepancy", ja: "そうい", romaji: "soui", pos: "名詞" },
    { no: 42, en: "feasibility", ja: "かのうせい", romaji: "kanousei", pos: "名詞" },
    { no: 43, en: "fluctuation", ja: "へんどう", romaji: "hendou", pos: "名詞" },
    { no: 44, en: "guideline", ja: "ししん", romaji: "shishin", pos: "名詞" },
    { no: 45, en: "in-house", ja: "しゃないの", romaji: "shanai no", pos: "形容詞" },
    { no: 46, en: "initiative", ja: "しゅどうけん", romaji: "shudouken", pos: "名詞" },
    { no: 47, en: "leverage", ja: "りようする", romaji: "riyou suru", pos: "動詞" },
    { no: 48, en: "milestone", ja: "まいろすとーん", romaji: "mairo sutoun", pos: "名詞" },
    { no: 49, en: "outsource", ja: "がいちゅうする", romaji: "gaichuu suru", pos: "動詞" },
    { no: 50, en: "oversee", ja: "かんとくする", romaji: "kantoku suru", pos: "動詞" },
    { no: 51, en: "proactive", ja: "ぜんちてきな", romaji: "zenchiteki na", pos: "形容詞" },
    { no: 52, en: "redundancy", ja: "じゅうふく", romaji: "juufuku", pos: "名詞" },
    { no: 53, en: "stakeholder", ja: "かんけいしゃ", romaji: "kankeisha", pos: "名詞" },
    { no: 54, en: "sustainable", ja: "じぞくかのうな", romaji: "jizoku kanou na", pos: "形容詞" },
    { no: 55, en: "turnover", ja: "じんいんりゅうどう", romaji: "jin'in ryuudou", pos: "名詞" },
    { no: 56, en: "accountability", ja: "せきにん", romaji: "sekinin", pos: "名詞" },
    { no: 57, en: "brainstorm", ja: "ぶれいんすとーむする", romaji: "bureinsutoumu suru", pos: "動詞" },
    { no: 58, en: "consecutive", ja: "れんぞくの", romaji: "renzoku no", pos: "形容詞" },
    { no: 59, en: "contingent", ja: "じょうけんつきの", romaji: "jouken tsuki no", pos: "形容詞" },
    { no: 60, en: "downsize", ja: "せいじんする", romaji: "seijin suru", pos: "動詞" },
    { no: 61, en: "empower", ja: "けんのうをあたえる", romaji: "kennou wo ataeru", pos: "動詞" },
    { no: 62, en: "expedite", ja: "すみやかにする", romaji: "sumiyaka ni suru", pos: "動詞" },
    { no: 63, en: "fluctuate", ja: "へんどうする", romaji: "hendou suru", pos: "動詞" },
    { no: 64, en: "forecast", ja: "よそくする", romaji: "yosoku suru", pos: "動詞" },
    { no: 65, en: "holistic", ja: "ぜんめんてきな", romaji: "zenmenteki na", pos: "形容詞" },
    { no: 66, en: "incur", ja: "こうむる", romaji: "koumuru", pos: "動詞" },
    { no: 67, en: "interim", ja: "ちゅうかんの", romaji: "chuukan no", pos: "形容詞" },
    { no: 68, en: "liaise", ja: "れんらくする", romaji: "renraku suru", pos: "動詞" },
    { no: 69, en: "merger", ja: "がっぺい", romaji: "gappei", pos: "名詞" },
    { no: 70, en: "multinational", ja: "たこくの", romaji: "takoku no", pos: "形容詞" },
    { no: 71, en: "overhaul", ja: "ぜんめんてきかい", romaji: "zenmenteki kai", pos: "名詞" },
    { no: 72, en: "oversight", ja: "かんとく", romaji: "kantoku", pos: "名詞" },
    { no: 73, en: "paradigm", ja: "ぱらだいむ", romaji: "paradaimu", pos: "名詞" },
    { no: 74, en: "procurement", ja: "ちゅうもん", romaji: "chuumon", pos: "名詞" },
    { no: 75, en: "reimburse", ja: "かんぺいする", romaji: "kanpei suru", pos: "動詞" },
    { no: 76, en: "restructure", ja: "さいへんせいする", romaji: "saihensei suru", pos: "動詞" },
    { no: 77, en: "retention", ja: "りゅうにん", romaji: "ryuunin", pos: "名詞" },
    { no: 78, en: "scalable", ja: "かくだいかのうな", romaji: "kakudai kanou na", pos: "形容詞" },
    { no: 79, en: "subsidy", ja: "ほじょきん", romaji: "hojokin", pos: "名詞" },
    { no: 80, en: "synergy", ja: "きょうどうこうか", romaji: "kyoudou kouka", pos: "名詞" },
    { no: 81, en: "tangible", ja: "ちかくできる", romaji: "chikaku dekiru", pos: "形容詞" },
    { no: 82, en: "transparent", ja: "とうめいな", romaji: "toumei na", pos: "形容詞" },
    { no: 83, en: "utilize", ja: "りようする", romaji: "riyou suru", pos: "動詞" },
    { no: 84, en: "workflow", ja: "わーくふろー", romaji: "waakufuroo", pos: "名詞" },
    { no: 85, en: "aftermath", ja: "じせい", romaji: "jisei", pos: "名詞" },
    { no: 86, en: "align", ja: "そろえる", romaji: "soroeru", pos: "動詞" },
    { no: 87, en: "appraisal", ja: "ひょうか", romaji: "hyouka", pos: "名詞" },
    { no: 88, en: "arbitrate", ja: "ちゅうさいする", romaji: "chuusai suru", pos: "動詞" },
    { no: 89, en: "assert", ja: "だんげんする", romaji: "dangen suru", pos: "動詞" },
    { no: 90, en: "commence", ja: "かいしする", romaji: "kaishi suru", pos: "動詞" },
    { no: 91, en: "comply", ja: "したがう", romaji: "shitagau", pos: "動詞" },
    { no: 92, en: "convey", ja: "つたえる", romaji: "tsutaeru", pos: "動詞" },
    { no: 93, en: "deduct", ja: "さしひく", romaji: "sashihiku", pos: "動詞" },
    { no: 94, en: "defer", ja: "えんきする", romaji: "enki suru", pos: "動詞" },
    { no: 95, en: "affiliate", ja: "しゅうせきする", romaji: "shuuseki suru", pos: "動詞" },
    { no: 96, en: "aggregate", ja: "しゅうごうする", romaji: "shuugou suru", pos: "動詞" },
    { no: 97, en: "amend", ja: "しゅうせいする", romaji: "shuusei suru", pos: "動詞" },
    { no: 98, en: "articulate", ja: "めいりょうにのべる", romaji: "meiryou ni noberu", pos: "動詞" },
    { no: 99, en: "complement", ja: "ほきょうする", romaji: "hokyou suru", pos: "動詞" },
    { no: 100, en: "convene", ja: "しゅうごうする", romaji: "shuugou suru", pos: "動詞" },
    { no: 101, en: "differentiate", ja: "くべつする", romaji: "kubetsu suru", pos: "動詞" },
    { no: 102, en: "disseminate", ja: "ふきゅうする", romaji: "fukyuu suru", pos: "動詞" },
    { no: 103, en: "endorse", ja: "しょうにんする", romaji: "shounin suru", pos: "動詞" },
    { no: 104, en: "enumerate", ja: "れっきょする", romaji: "rekkyo suru", pos: "動詞" },
    { no: 105, en: "envisage", ja: "そうぞうする", romaji: "souzou suru", pos: "動詞" },
    { no: 106, en: "eradicate", ja: "こくめつする", romaji: "kokumetsu suru", pos: "動詞" },
    { no: 107, en: "escalate", ja: "えすかれーとする", romaji: "esukareeto suru", pos: "動詞" },
    { no: 108, en: "evacuate", ja: "ひなんする", romaji: "hinan suru", pos: "動詞" },
    { no: 109, en: "exemplify", ja: "れいしょうする", romaji: "reishou suru", pos: "動詞" },
    { no: 110, en: "expire", ja: "まんきする", romaji: "manki suru", pos: "動詞" },
    { no: 111, en: "finalize", ja: "けっていする", romaji: "kettei suru", pos: "動詞" },
    { no: 112, en: "fluctuate", ja: "へんどうする", romaji: "hendou suru", pos: "動詞" },
    { no: 113, en: "formulate", ja: "もくろみをたてる", romaji: "mokuromi wo tateru", pos: "動詞" },
    { no: 114, en: "foster", ja: "そだてる", romaji: "sodateru", pos: "動詞" },
    { no: 115, en: "guarantee", ja: "ほしょうする", romaji: "hoshou suru", pos: "動詞" },
    { no: 116, en: "harmonize", ja: "ちょうわさせる", romaji: "chouwa saseru", pos: "動詞" },
    { no: 117, en: "hypothesize", ja: "かせつをたてる", romaji: "kasetsu wo tateru", pos: "動詞" },
    { no: 118, en: "incorporate", ja: "とりいれる", romaji: "toriireru", pos: "動詞" },
    { no: 119, en: "indicate", ja: "しめす", romaji: "shimesu", pos: "動詞" },
    { no: 120, en: "infer", ja: "すいそくする", romaji: "suisoku suru", pos: "動詞" },
    { no: 121, en: "integrate", ja: "せつごうする", romaji: "setsugou suru", pos: "動詞" },
    { no: 122, en: "intervene", ja: "かいにゅうする", romaji: "kainyuu suru", pos: "動詞" },
    { no: 123, en: "invalidate", ja: "むこうにする", romaji: "mukou ni suru", pos: "動詞" },
    { no: 124, en: "legitimize", ja: "ごうほうかする", romaji: "gouhouka suru", pos: "動詞" },
    { no: 125, en: "liquidate", ja: "せいさんする", romaji: "seisan suru", pos: "動詞" },
    { no: 126, en: "modify", ja: "しゅうせいする", romaji: "shuusei suru", pos: "動詞" },
    { no: 127, en: "monitor", ja: "かんしする", romaji: "kanshi suru", pos: "動詞" },
    { no: 128, en: "negotiate", ja: "こうしょうする", romaji: "koushou suru", pos: "動詞" },
    { no: 129, en: "nominate", ja: "ていめいする", romaji: "teimei suru", pos: "動詞" },
    { no: 130, en: "notify", ja: "つうちする", romaji: "tsuuchi suru", pos: "動詞" },
    { no: 131, en: "nullify", ja: "むこうにする", romaji: "mukou ni suru", pos: "動詞" },
    { no: 132, en: "obsolete", ja: "ふるくなった", romaji: "furuku natta", pos: "形容詞" },
    { no: 133, en: "outline", ja: "あらすじ", romaji: "arasuji", pos: "名詞" },
    { no: 134, en: "overlap", ja: "ちょうふくする", romaji: "choufuku suru", pos: "動詞" },
    { no: 135, en: "penalize", ja: "ばっする", romaji: "bassuru", pos: "動詞" },
    { no: 136, en: "perceive", ja: "ちかくする", romaji: "chikaku suru", pos: "動詞" },
    { no: 137, en: "petition", ja: "ちんがんする", romaji: "chingan suru", pos: "動詞" },
    { no: 138, en: "postpone", ja: "えんきする", romaji: "enki suru", pos: "動詞" },
    { no: 139, en: "preclude", ja: "ふせぐ", romaji: "fusegu", pos: "動詞" },
    { no: 140, en: "predetermine", ja: "あらかじめきめる", romaji: "arakajime kimeru", pos: "動詞" },
    { no: 141, en: "prescribe", ja: "しじする", romaji: "shiji suru", pos: "動詞" },
    { no: 142, en: "preserve", ja: "ほぞんする", romaji: "hozon suru", pos: "動詞" },
    { no: 143, en: "preside", ja: "しゅさいする", romaji: "shusai suru", pos: "動詞" },
    { no: 144, en: "prevail", ja: "しょうする", romaji: "shou suru", pos: "動詞" },
    { no: 145, en: "prohibit", ja: "きんしする", romaji: "kinshi suru", pos: "動詞" },
    { no: 146, en: "promulgate", ja: "ふれつする", romaji: "furetsu suru", pos: "動詞" },
    { no: 147, en: "prosecute", ja: "きそする", romaji: "kiso suru", pos: "動詞" },
    { no: 148, en: "provision", ja: "きょうきゅう", romaji: "kyoukyuu", pos: "名詞" },
    { no: 149, en: "ratify", ja: "しょうにんする", romaji: "shounin suru", pos: "動詞" },
    { no: 150, en: "reconcile", ja: "ちょうていする", romaji: "choutei suru", pos: "動詞" },
    { no: 151, en: "recur", ja: "さいはつする", romaji: "saihatsu suru", pos: "動詞" },
    { no: 152, en: "refute", ja: "はんばくする", romaji: "hanbaku suru", pos: "動詞" },
    { no: 153, en: "reinstate", ja: "ふくしょくする", romaji: "fukushoku suru", pos: "動詞" },
    { no: 154, en: "relinquish", ja: "ほうきする", romaji: "houki suru", pos: "動詞" },
    { no: 155, en: "relocate", ja: "いてんする", romaji: "iten suru", pos: "動詞" },
    { no: 156, en: "remunerate", ja: "ほうしゅうする", romaji: "houshuu suru", pos: "動詞" },
    { no: 157, en: "renovate", ja: "しゅうりする", romaji: "shuuri suru", pos: "動詞" },
    { no: 158, en: "repel", ja: "はねかえす", romaji: "hanekaesu", pos: "動詞" },
    { no: 159, en: "replicate", ja: "ふせいする", romaji: "fusei suru", pos: "動詞" },
    { no: 160, en: "repudiate", ja: "きょひする", romaji: "kyohi suru", pos: "動詞" },
    { no: 161, en: "reschedule", ja: "すけじゅーるをかえる", romaji: "sukejuuru wo kaeru", pos: "動詞" },
    { no: 162, en: "reside", ja: "すむ", romaji: "sumu", pos: "動詞" },
    { no: 163, en: "resign", ja: "じにんする", romaji: "jinin suru", pos: "動詞" },
    { no: 164, en: "resume", ja: "さいかいする", romaji: "saikai suru", pos: "動詞" },
    { no: 165, en: "retrieve", ja: "とりもどす", romaji: "torimodosu", pos: "動詞" },
    { no: 166, en: "revoke", ja: "とりけす", romaji: "torikesu", pos: "動詞" },
    { no: 167, en: "sanction", ja: "けんきをあたえる", romaji: "kenki wo ataeru", pos: "動詞" },
    { no: 168, en: "scrutinize", ja: "けんさする", romaji: "kensa suru", pos: "動詞" },
    { no: 169, en: "sever", ja: "たちきる", romaji: "tachikiru", pos: "動詞" },
    { no: 170, en: "solicit", ja: "もとめる", romaji: "motomeru", pos: "動詞" },
    { no: 171, en: "speculate", ja: "すいそくする", romaji: "suisoku suru", pos: "動詞" },
    { no: 172, en: "stipulate", ja: "きていする", romaji: "kitei suru", pos: "動詞" },
    { no: 173, en: "subordinate", ja: "したくみの", romaji: "shitakumi no", pos: "形容詞" },
    { no: 174, en: "substantiate", ja: "しょうめいする", romaji: "shoumei suru", pos: "動詞" },
    { no: 175, en: "supervise", ja: "かんとくする", romaji: "kantoku suru", pos: "動詞" },
    { no: 176, en: "supplement", ja: "ほきょうする", romaji: "hokyou suru", pos: "動詞" },
    { no: 177, en: "surpass", ja: "こえる", romaji: "koeru", pos: "動詞" },
    { no: 178, en: "susceptible", ja: "びんかんな", romaji: "binkan na", pos: "形容詞" },
    { no: 179, en: "terminology", ja: "じゅつご", romaji: "jutsugo", pos: "名詞" },
    { no: 180, en: "testify", ja: "しょうげんする", romaji: "shougen suru", pos: "動詞" },
    { no: 181, en: "tolerate", ja: "たいにんする", romaji: "tainin suru", pos: "動詞" },
    { no: 182, en: "transact", ja: "とりひきする", romaji: "torihiki suru", pos: "動詞" },
    { no: 183, en: "transcend", ja: "こえる", romaji: "koeru", pos: "動詞" },
    { no: 184, en: "transcribe", ja: "うつす", romaji: "utsusu", pos: "動詞" },
    { no: 185, en: "transpire", ja: "あきらかになる", romaji: "akiraka ni naru", pos: "動詞" },
    { no: 186, en: "undermine", ja: "そこなう", romaji: "sokonau", pos: "動詞" },
    { no: 187, en: "validate", ja: "ゆうこうにする", romaji: "yuukou ni suru", pos: "動詞" },
    { no: 188, en: "verbalize", ja: "ことばであらわす", romaji: "kotoba de arawasu", pos: "動詞" },
    { no: 189, en: "verify", ja: "かくにんする", romaji: "kakunin suru", pos: "動詞" },
    { no: 190, en: "waive", ja: "きょひする", romaji: "kyohi suru", pos: "動詞" },
    { no: 191, en: "warrant", ja: "しょうこ", romaji: "shouko", pos: "名詞" },
    { no: 192, en: "withhold", ja: "おさえる", romaji: "osaeru", pos: "動詞" },
    { no: 193, en: "yield", ja: "しゅうかく", romaji: "shuukaku", pos: "名詞" },
    { no: 194, en: "zeal", ja: "ねつい", romaji: "netsui", pos: "名詞" },
    { no: 195, en: "abolition", ja: "はいし", romaji: "haishi", pos: "名詞" },
    { no: 196, en: "adherence", ja: "じゅんしゅ", romaji: "junshu", pos: "名詞" },
    { no: 197, en: "adjourn", ja: "きゅうかいする", romaji: "kyuukai suru", pos: "動詞" },
    { no: 198, en: "affidavit", ja: "ていしょ", romaji: "teisho", pos: "名詞" },
    { no: 199, en: "aggregation", ja: "しゅうけい", romaji: "shuukei", pos: "名詞" },
    { no: 200, en: "allegation", ja: "しんそう", romaji: "shinsou", pos: "名詞" },
    { no: 201, en: "amendment", ja: "しゅうせいあん", romaji: "shuusei an", pos: "名詞" },
    { no: 202, en: "appendix", ja: "ふろく", romaji: "furoku", pos: "名詞" },
    { no: 203, en: "appropriation", ja: "しさん", romaji: "shisan", pos: "名詞" },
    { no: 204, en: "arbitrator", ja: "ちゅうさいにん", romaji: "chuusainin", pos: "名詞" },
    { no: 205, en: "attribution", ja: "きせい", romaji: "kisei", pos: "名詞" },
    { no: 206, en: "auditor", ja: "かんさにん", romaji: "kansanin", pos: "名詞" },
    { no: 207, en: "authorization", ja: "けんきづけ", romaji: "kenkizuke", pos: "名詞" },
    { no: 208, en: "automation", ja: "じどうか", romaji: "jidouka", pos: "名詞" },
    { no: 209, en: "bilateral", ja: "そうごの", romaji: "sougo no", pos: "形容詞" },
    { no: 210, en: "bylaw", ja: "じょうれい", romaji: "jourei", pos: "名詞" },
    { no: 211, en: "capitalization", ja: "しほんか", romaji: "shihonka", pos: "名詞" },
    { no: 212, en: "collateral", ja: "ていとう", romaji: "teitou", pos: "名詞" },
    { no: 213, en: "compensation", ja: "ほしょう", romaji: "hoshou", pos: "名詞" },
    { no: 214, en: "confirmation", ja: "かくにん", romaji: "kakunin", pos: "名詞" },
    { no: 215, en: "consolidation", ja: "とうごう", romaji: "tougou", pos: "名詞" },
    { no: 216, en: "constitution", ja: "けんぽう", romaji: "kenpou", pos: "名詞" },
    { no: 217, en: "consultation", ja: "そうだん", romaji: "soudan", pos: "名詞" },
    { no: 218, en: "contamination", ja: "おせん", romaji: "osen", pos: "名詞" },
    { no: 219, en: "continuation", ja: "けいぞく", romaji: "keizoku", pos: "名詞" },
    { no: 220, en: "contravention", ja: "いはん", romaji: "ihan", pos: "名詞" },
    { no: 221, en: "convention", ja: "きょうぎ", romaji: "kyougi", pos: "名詞" },
    { no: 222, en: "conveyance", ja: "てんそう", romaji: "tensou", pos: "名詞" },
    { no: 223, en: "credential", ja: "しょうめいしょ", romaji: "shoumeisho", pos: "名詞" },
    { no: 224, en: "default", ja: "けいやくいはん", romaji: "keiyaku ihan", pos: "名詞" },
    { no: 225, en: "deferral", ja: "えんき", romaji: "enki", pos: "名詞" },
    { no: 226, en: "deficiency", ja: "けっかん", romaji: "kekkan", pos: "名詞" },
    { no: 227, en: "delegation", ja: "だいひょうだん", romaji: "daihyou dan", pos: "名詞" },
    { no: 228, en: "designation", ja: "してい", romaji: "shitei", pos: "名詞" },
    { no: 229, en: "disbursement", ja: "しはらい", romaji: "shiharai", pos: "名詞" },
    { no: 230, en: "disclosure", ja: "かいじ", romaji: "kaiji", pos: "名詞" },
    { no: 231, en: "discretion", ja: "さいぎ", romaji: "saigi", pos: "名詞" },
    { no: 232, en: "dissolution", ja: "かいさん", romaji: "kaisan", pos: "名詞" },
    { no: 233, en: "distributor", ja: "はいきゅうしゃ", romaji: "haikyuu sha", pos: "名詞" },
    { no: 234, en: "diversification", ja: "たようか", romaji: "tayouka", pos: "名詞" },
    { no: 235, en: "endorsement", ja: "しょうにん", romaji: "shounin", pos: "名詞" },
    { no: 236, en: "enforcement", ja: "きょうせい", romaji: "kyousei", pos: "名詞" },
    { no: 237, en: "entitlement", ja: "けんり", romaji: "kenri", pos: "名詞" },
    { no: 238, en: "exclusion", ja: "じょがい", romaji: "jogai", pos: "名詞" },
    { no: 239, en: "expiration", ja: "まんき", romaji: "manki", pos: "名詞" },
    { no: 240, en: "franchise", ja: "こんきょけん", romaji: "konkyoken", pos: "名詞" },
    { no: 241, en: "grievance", ja: "ふまん", romaji: "fuman", pos: "名詞" },
    { no: 242, en: "indemnity", ja: "ほしょう", romaji: "hoshou", pos: "名詞" },
    { no: 243, en: "insolvency", ja: "とうは", romaji: "touha", pos: "名詞" },
    { no: 244, en: "jurisdiction", ja: "しょかん", romaji: "shokan", pos: "名詞" },
    { no: 245, en: "litigation", ja: "そしょう", romaji: "soshou", pos: "名詞" },
    { no: 246, en: "obligation", ja: "ぎむ", romaji: "gimu", pos: "名詞" },
    { no: 247, en: "remedy", ja: "さいせい", romaji: "saisei", pos: "名詞" },
    { no: 248, en: "remittance", ja: "そうきん", romaji: "soukin", pos: "名詞" },
    { no: 249, en: "reparation", ja: "ほしょう", romaji: "hoshou", pos: "名詞" },
    { no: 250, en: "revocation", ja: "とりけし", romaji: "torikeshi", pos: "名詞" }
];

const part1WordList = [
    { no: 1, en: "accountant", ja: "かいけいし", romaji: "kaikeishi", pos: "名詞" },
    { no: 2, en: "appointment", ja: "よやく", romaji: "yoyaku", pos: "名詞" },
    { no: 3, en: "suggestion", ja: "ていあん", romaji: "teian", pos: "名詞" },
    { no: 4, en: "instruction", ja: "しじ", romaji: "shiji", pos: "名詞" },
    { no: 5, en: "delivery", ja: "はいとう", romaji: "haitou", pos: "名詞" },
    { no: 6, en: "manufacturer", ja: "せいぞうぎょうしゃ", romaji: "seizougyousha", pos: "名詞" },
    { no: 7, en: "recommendation", ja: "すいせん", romaji: "suisen", pos: "名詞" },
    { no: 8, en: "strategy", ja: "せんりゃく", romaji: "senryaku", pos: "名詞" },
    { no: 9, en: "resident", ja: "じゅうみん", romaji: "juumin", pos: "名詞" },
    { no: 10, en: "plant", ja: "こうじょう", romaji: "koujou", pos: "名詞" },
    { no: 11, en: "firm", ja: "かいしゃ", romaji: "kaisha", pos: "名詞" },
    { no: 12, en: "minute", ja: "ぎじろく", romaji: "gijiroku", pos: "名詞" },
    { no: 13, en: "applicable", ja: "てきようできる", romaji: "tekiyou dekiru", pos: "形容詞" },
    { no: 14, en: "cabinet", ja: "しょるいだな", romaji: "shoruidana", pos: "名詞" },
    { no: 15, en: "calculate", ja: "けいさんする", romaji: "keisan suru", pos: "動詞" },
    { no: 16, en: "cancellation", ja: "とりけし", romaji: "torikeshi", pos: "名詞" },
    { no: 17, en: "cargo", ja: "かもつ", romaji: "kamotsu", pos: "名詞" },
    { no: 18, en: "catering", ja: "しだし", romaji: "shidashi", pos: "名詞" },
    { no: 19, en: "clarify", ja: "めいかくにする", romaji: "meikaku ni suru", pos: "動詞" },
    { no: 20, en: "clerk", ja: "てんいん", romaji: "ten'in", pos: "名詞" },
    { no: 21, en: "consent", ja: "どうい", romaji: "doui", pos: "名詞" },
    { no: 22, en: "deduct", ja: "さしひく", romaji: "sashihiku", pos: "動詞" },
    { no: 23, en: "defective", ja: "けっかんのある", romaji: "kekkan no aru", pos: "形容詞" },
    { no: 24, en: "departure", ja: "しゅっぱつ", romaji: "shuppatsu", pos: "名詞" },
    { no: 25, en: "distribute", ja: "はいふする", romaji: "haifu suru", pos: "動詞" },
    { no: 26, en: "enclose", ja: "どうふする", romaji: "doufu suru", pos: "動詞" },
    { no: 27, en: "expansion", ja: "かくちょう", romaji: "kakuchou", pos: "名詞" },
    { no: 28, en: "inspection", ja: "けんさ", romaji: "kensa", pos: "名詞" },
    { no: 29, en: "inventory", ja: "ざいこ", romaji: "zaiko", pos: "名詞" },
    { no: 30, en: "invest", ja: "とうしする", romaji: "toushi suru", pos: "動詞" },
    { no: 31, en: "labor", ja: "ろうどう", romaji: "roudou", pos: "名詞" },
    { no: 32, en: "lease", ja: "ちんたい", romaji: "chintai", pos: "名詞" },
    { no: 33, en: "license", ja: "めんきょ", romaji: "menkyo", pos: "名詞" },
    { no: 34, en: "location", ja: "いち", romaji: "ichi", pos: "名詞" },
    { no: 35, en: "management", ja: "かんり", romaji: "kanri", pos: "名詞" },
    { no: 36, en: "manual", ja: "せつめいしょ", romaji: "setsumeisho", pos: "名詞" },
    { no: 37, en: "manufacture", ja: "せいぞうする", romaji: "seizou suru", pos: "動詞" },
    { no: 38, en: "material", ja: "ざいりょう", romaji: "zairyou", pos: "名詞" },
    { no: 39, en: "maximum", ja: "さいだい", romaji: "saidai", pos: "名詞" },
    { no: 40, en: "minimum", ja: "さいしょう", romaji: "saishou", pos: "名詞" },
    { no: 41, en: "negotiate", ja: "こうしょうする", romaji: "koushou suru", pos: "動詞" },
    { no: 42, en: "operation", ja: "そうさ", romaji: "sousa", pos: "名詞" },
    { no: 43, en: "obtain", ja: "える", romaji: "eru", pos: "動詞" },
    { no: 44, en: "operate", ja: "うんえいする", romaji: "un'ei suru", pos: "動詞" },
    { no: 45, en: "original", ja: "げんぽんの", romaji: "genpon no", pos: "形容詞" },
    { no: 46, en: "package", ja: "こづつみ", romaji: "kozutsumi", pos: "名詞" },
    { no: 47, en: "participant", ja: "さんかしゃ", romaji: "sankasha", pos: "名詞" },
    { no: 48, en: "participate", ja: "さんかする", romaji: "sanka suru", pos: "動詞" },
    { no: 49, en: "partnership", ja: "きょうどう", romaji: "kyoudou", pos: "名詞" },
    { no: 50, en: "percentage", ja: "ぱーせんと", romaji: "paasento", pos: "名詞" },
    { no: 51, en: "portion", ja: "ぶぶん", romaji: "bubun", pos: "名詞" },
    { no: 52, en: "postpone", ja: "えんきする", romaji: "enki suru", pos: "動詞" },
    { no: 53, en: "prefer", ja: "このむ", romaji: "konomu", pos: "動詞" },
    { no: 54, en: "premium", ja: "ほけんりょう", romaji: "hokenryou", pos: "名詞" },
    { no: 55, en: "present", ja: "ていじする", romaji: "teiji suru", pos: "動詞" },
    { no: 56, en: "produce", ja: "せいさんする", romaji: "seisan suru", pos: "動詞" },
    { no: 57, en: "progress", ja: "しんちょく", romaji: "shinchoku", pos: "名詞" },
    { no: 58, en: "promote", ja: "そくしんする", romaji: "sokushin suru", pos: "動詞" },
    { no: 59, en: "qualify", ja: "しかくをえる", romaji: "shikaku wo eru", pos: "動詞" },
    { no: 60, en: "quote", ja: "みつもり", romaji: "mitsumori", pos: "名詞" },
    { no: 61, en: "refer", ja: "さんしょうする", romaji: "sanshou suru", pos: "動詞" },
    { no: 62, en: "register", ja: "とうろくする", romaji: "touroku suru", pos: "動詞" },
    { no: 63, en: "retail", ja: "こうり", romaji: "kouri", pos: "名詞" },
    { no: 64, en: "software", ja: "そふとうぇあ", romaji: "sofutouea", pos: "名詞" },
    { no: 65, en: "subsidiary", ja: "こがいしゃ", romaji: "kogaisha", pos: "名詞" },
    { no: 66, en: "supplier", ja: "きょうきゅうしゃ", romaji: "kyoukyuusha", pos: "名詞" },
    { no: 67, en: "transaction", ja: "とりひき", romaji: "torihiki", pos: "名詞" },
    { no: 68, en: "warranty", ja: "ほしょう", romaji: "hoshou", pos: "名詞" },
    { no: 69, en: "attendance", ja: "しゅっせき", romaji: "shusseki", pos: "名詞" },
    { no: 70, en: "authorize", ja: "きょかする", romaji: "kyoka suru", pos: "動詞" },
    { no: 71, en: "automate", ja: "じどうかする", romaji: "jidouka suru", pos: "動詞" },
    { no: 72, en: "compliance", ja: "じゅんしゅ", romaji: "junshu", pos: "名詞" },
    { no: 73, en: "confidential", ja: "きみつの", romaji: "kimitsu no", pos: "形容詞" },
    { no: 74, en: "consolidate", ja: "とうごうする", romaji: "tougou suru", pos: "動詞" },
    { no: 75, en: "coordinate", ja: "ちょうせいする", romaji: "chousei suru", pos: "動詞" },
    { no: 76, en: "delegate", ja: "いにんする", romaji: "inin suru", pos: "動詞" },
    { no: 77, en: "demonstrate", ja: "じつえんする", romaji: "jitsuen suru", pos: "動詞" },
    { no: 78, en: "documentation", ja: "しょるいか", romaji: "shorui ka", pos: "名詞" },
    { no: 79, en: "eligible", ja: "しかくのある", romaji: "shikaku no aru", pos: "形容詞" },
    { no: 80, en: "establish", ja: "せつりつする", romaji: "setsuritsu suru", pos: "動詞" },
    { no: 81, en: "expertise", ja: "せんもんちしき", romaji: "senmon chishiki", pos: "名詞" },
    { no: 82, en: "facilitate", ja: "えんかつにする", romaji: "enkatsu ni suru", pos: "動詞" },
    { no: 83, en: "administer", ja: "かんりする", romaji: "kanri suru", pos: "動詞" },
    { no: 84, en: "incentive", ja: "どうきづけ", romaji: "doukizuke", pos: "名詞" },
    { no: 85, en: "infrastructure", ja: "きばん", romaji: "kiban", pos: "名詞" },
    { no: 86, en: "innovative", ja: "かくしんてきな", romaji: "kakushinteki na", pos: "形容詞" },
    { no: 87, en: "liaison", ja: "れんらくやく", romaji: "renrakuyaku", pos: "名詞" },
    { no: 88, en: "mandatory", ja: "ひっすの", romaji: "hissu no", pos: "形容詞" },
    { no: 89, en: "optimize", ja: "さいてきかする", romaji: "saiteki ka suru", pos: "動詞" },
    { no: 90, en: "prioritize", ja: "ゆうせんする", romaji: "yuusen suru", pos: "動詞" },
    { no: 91, en: "protocol", ja: "てじゅん", romaji: "tejun", pos: "名詞" },
    { no: 92, en: "qualification", ja: "しかく", romaji: "shikaku", pos: "名詞" },
    { no: 93, en: "redundant", ja: "よぶんな", romaji: "yobun na", pos: "形容詞" },
    { no: 94, en: "regulatory", ja: "きせいの", romaji: "kisei no", pos: "形容詞" },
    { no: 95, en: "streamline", ja: "ごうりかする", romaji: "gourika suru", pos: "動詞" },
    { no: 96, en: "terminate", ja: "しゅうりょうする", romaji: "shuuryou suru", pos: "動詞" },
    { no: 97, en: "valid", ja: "ゆうこうな", romaji: "yuukou na", pos: "形容詞" },
    { no: 98, en: "verify", ja: "かくにんする", romaji: "kakunin suru", pos: "動詞" },
    { no: 99, en: "accommodate", ja: "しゅうようする", romaji: "shuuyou suru", pos: "動詞" },
    { no: 100, en: "acknowledge", ja: "みとめる", romaji: "mitomeru", pos: "動詞" },
    { no: 101, en: "information", ja: "じょうほう", romaji: "jouhou", pos: "名詞" },
    { no: 102, en: "process", ja: "ぷろせす", romaji: "purosesu", pos: "名詞" },
    { no: 103, en: "system", ja: "しすてむ", romaji: "shisutemu", pos: "名詞" },
    { no: 104, en: "policy", ja: "ほうしん", romaji: "houshin", pos: "名詞" },
    { no: 105, en: "price", ja: "ねだん", romaji: "nedan", pos: "名詞" },
    { no: 106, en: "result", ja: "けっか", romaji: "kekka", pos: "名詞" },
    { no: 107, en: "role", ja: "やくわり", romaji: "yakuwari", pos: "名詞" },
    { no: 108, en: "number", ja: "かず", romaji: "kazu", pos: "名詞" },
    { no: 109, en: "area", ja: "ちいき", romaji: "chiiki", pos: "名詞" },
    { no: 110, en: "plan", ja: "けいかく", romaji: "keikaku", pos: "名詞" },
    { no: 111, en: "program", ja: "ぷろぐらむ", romaji: "puroguramu", pos: "名詞" },
    { no: 112, en: "research", ja: "けんきゅう", romaji: "kenkyuu", pos: "名詞" },
    { no: 113, en: "staff", ja: "しょくいん", romaji: "shokuin", pos: "名詞" },
    { no: 114, en: "support", ja: "しえん", romaji: "shien", pos: "名詞" },
    { no: 115, en: "training", ja: "くんれん", romaji: "kunren", pos: "名詞" },
    { no: 116, en: "level", ja: "すいじゅん", romaji: "suijun", pos: "名詞" },
    { no: 117, en: "type", ja: "しゅるい", romaji: "shurui", pos: "名詞" },
    { no: 118, en: "rate", ja: "りつ", romaji: "ritsu", pos: "名詞" },
    { no: 119, en: "risk", ja: "りすく", romaji: "risuku", pos: "名詞" },
    { no: 120, en: "value", ja: "かち", romaji: "kachi", pos: "名詞" },
    { no: 121, en: "action", ja: "こうどう", romaji: "koudou", pos: "名詞" },
    { no: 122, en: "activity", ja: "かつどう", romaji: "katsudou", pos: "名詞" },
    { no: 123, en: "amount", ja: "がく", romaji: "gaku", pos: "名詞" },
    { no: 124, en: "approach", ja: "あぷろーち", romaji: "apuroochi", pos: "名詞" },
    { no: 125, en: "assessment", ja: "ひょうか", romaji: "hyouka", pos: "名詞" },
    { no: 126, en: "authority", ja: "けんげん", romaji: "kengen", pos: "名詞" },
    { no: 127, en: "balance", ja: "ばらんす", romaji: "baransu", pos: "名詞" },
    { no: 128, en: "basis", ja: "きそ", romaji: "kiso", pos: "名詞" },
    { no: 129, en: "benefit", ja: "りえき", romaji: "rieki", pos: "名詞" },
    { no: 130, en: "category", ja: "かてごりー", romaji: "kategori", pos: "名詞" },
    { no: 131, en: "change", ja: "へんこう", romaji: "henkou", pos: "名詞" },
    { no: 132, en: "choice", ja: "せんたく", romaji: "sentaku", pos: "名詞" },
    { no: 133, en: "comment", ja: "こめんと", romaji: "komento", pos: "名詞" },
    { no: 134, en: "commission", ja: "こみっしょん", romaji: "komisshon", pos: "名詞" },
    { no: 135, en: "commitment", ja: "こみっとめんと", romaji: "komittomento", pos: "名詞" },
    { no: 136, en: "community", ja: "こみゅにてぃ", romaji: "komyuniti", pos: "名詞" },
    { no: 137, en: "comparison", ja: "ひかく", romaji: "hikaku", pos: "名詞" },
    { no: 138, en: "competition", ja: "きょうそう", romaji: "kyousou", pos: "名詞" },
    { no: 139, en: "complex", ja: "ふくざつな", romaji: "fukuzatsu na", pos: "形容詞" },
    { no: 140, en: "concept", ja: "がいねん", romaji: "gainen", pos: "名詞" },
    { no: 141, en: "concern", ja: "しんぱい", romaji: "shinpai", pos: "名詞" },
    { no: 142, en: "conclusion", ja: "けつろん", romaji: "ketsuron", pos: "名詞" },
    { no: 143, en: "confidence", ja: "しんらい", romaji: "shinrai", pos: "名詞" },
    { no: 144, en: "conflict", ja: "たいりつ", romaji: "tairitsu", pos: "名詞" },
    { no: 145, en: "connection", ja: "せつぞく", romaji: "setsuzoku", pos: "名詞" },
    { no: 146, en: "consequence", ja: "けっか", romaji: "kekka", pos: "名詞" },
    { no: 147, en: "consideration", ja: "けんりょう", romaji: "kenryou", pos: "名詞" },
    { no: 148, en: "constant", ja: "じょうすう", romaji: "jousuu", pos: "名詞" },
    { no: 149, en: "construction", ja: "けんせつ", romaji: "kensetsu", pos: "名詞" },
    { no: 150, en: "context", ja: "ぶんみゃく", romaji: "bunmyaku", pos: "名詞" },
    { no: 151, en: "control", ja: "こんとろーる", romaji: "kontorooru", pos: "名詞" },
    { no: 152, en: "convention", ja: "きまり", romaji: "kimari", pos: "名詞" },
    { no: 153, en: "coverage", ja: "かばれっじ", romaji: "kabarejji", pos: "名詞" },
    { no: 154, en: "creation", ja: "そうぞう", romaji: "souzou", pos: "名詞" },
    { no: 155, en: "criteria", ja: "きじゅん", romaji: "kijun", pos: "名詞" },
    { no: 156, en: "damage", ja: "そんがい", romaji: "songai", pos: "名詞" },
    { no: 157, en: "data", ja: "でーた", romaji: "deeta", pos: "名詞" },
    { no: 158, en: "decrease", ja: "げんしょう", romaji: "genshou", pos: "名詞" },
    { no: 159, en: "definition", ja: "ていぎ", romaji: "teigi", pos: "名詞" },
    { no: 160, en: "demand", ja: "じゅよう", romaji: "juyou", pos: "名詞" },
    { no: 161, en: "demonstration", ja: "じっれい", romaji: "jitsurei", pos: "名詞" },
    { no: 162, en: "development", ja: "かいはつ", romaji: "kaihatsu", pos: "名詞" },
    { no: 163, en: "difference", ja: "ちがい", romaji: "chigai", pos: "名詞" },
    { no: 164, en: "difficulty", ja: "こんなん", romaji: "konnan", pos: "名詞" },
    { no: 165, en: "effect", ja: "こうか", romaji: "kouka", pos: "名詞" },
    { no: 166, en: "element", ja: "ようそ", romaji: "youso", pos: "名詞" },
    { no: 167, en: "emphasis", ja: "きょうちょう", romaji: "kyouchou", pos: "名詞" },
    { no: 168, en: "employment", ja: "こよう", romaji: "koyou", pos: "名詞" },
    { no: 169, en: "energy", ja: "えねるぎー", romaji: "enerugii", pos: "名詞" },
    { no: 170, en: "error", ja: "えらー", romaji: "eraa", pos: "名詞" },
    { no: 171, en: "establishment", ja: "せつりつ", romaji: "setsuritsu", pos: "名詞" },
    { no: 172, en: "evaluation", ja: "ひょうか", romaji: "hyouka", pos: "名詞" },
    { no: 173, en: "event", ja: "いべんと", romaji: "ibento", pos: "名詞" },
    { no: 174, en: "evidence", ja: "しょうこ", romaji: "shouko", pos: "名詞" },
    { no: 175, en: "example", ja: "れい", romaji: "rei", pos: "名詞" },
    { no: 176, en: "exception", ja: "れいがい", romaji: "reigai", pos: "名詞" },
    { no: 177, en: "expansion", ja: "かくだい", romaji: "kakudai", pos: "名詞" },
    { no: 178, en: "expectation", ja: "きたい", romaji: "kitai", pos: "名詞" },
    { no: 179, en: "expert", ja: "せんもんか", romaji: "senmonka", pos: "名詞" },
    { no: 180, en: "explanation", ja: "せつめい", romaji: "setsumei", pos: "名詞" },
    { no: 181, en: "extent", ja: "はんい", romaji: "han'i", pos: "名詞" },
    { no: 182, en: "failure", ja: "しっぱい", romaji: "shippai", pos: "名詞" },
    { no: 183, en: "feature", ja: "とくちょう", romaji: "tokuchou", pos: "名詞" },
    { no: 184, en: "fee", ja: "りょうきん", romaji: "ryoukin", pos: "名詞" },
    { no: 185, en: "file", ja: "ふぁいる", romaji: "fairu", pos: "名詞" },
    { no: 186, en: "finding", ja: "はっけん", romaji: "hakken", pos: "名詞" },
    { no: 187, en: "flow", ja: "ふろー", romaji: "furoo", pos: "名詞" },
    { no: 188, en: "fund", ja: "ききん", romaji: "kikin", pos: "名詞" },
    { no: 189, en: "guideline", ja: "がいどらいん", romaji: "gaidorain", pos: "名詞" },
    { no: 190, en: "handling", ja: "とりあつかい", romaji: "toriatsukai", pos: "名詞" },
    { no: 191, en: "impact", ja: "えいきょう", romaji: "eikyou", pos: "名詞" },
    { no: 192, en: "importance", ja: "じゅうようせい", romaji: "juuyousei", pos: "名詞" },
    { no: 193, en: "improvement", ja: "かいぜん", romaji: "kaizen", pos: "名詞" },
    { no: 194, en: "incentive", ja: "しどうきん", romaji: "shidoukin", pos: "名詞" },
    { no: 195, en: "indication", ja: "しめすこと", romaji: "shimesu koto", pos: "名詞" },
    { no: 196, en: "individual", ja: "こじん", romaji: "kojin", pos: "名詞" },
    { no: 197, en: "influence", ja: "えいきょう", romaji: "eikyou", pos: "名詞" },
    { no: 198, en: "initiative", ja: "しゅどう", romaji: "shudou", pos: "名詞" },
    { no: 199, en: "input", ja: "いんぷっと", romaji: "inputto", pos: "名詞" },
    { no: 200, en: "inspection", ja: "けんさ", romaji: "kensa", pos: "名詞" },
    { no: 201, en: "instance", ja: "れい", romaji: "rei", pos: "名詞" },
    { no: 202, en: "instruction", ja: "しじ", romaji: "shiji", pos: "名詞" },
    { no: 203, en: "insurance", ja: "ほけん", romaji: "hoken", pos: "名詞" },
    { no: 204, en: "integration", ja: "せつごう", romaji: "setsugou", pos: "名詞" },
    { no: 205, en: "interaction", ja: "そうごさよう", romaji: "sougo sayou", pos: "名詞" },
    { no: 206, en: "interest", ja: "きょうみ", romaji: "kyoumi", pos: "名詞" },
    { no: 207, en: "introduction", ja: "しょうかい", romaji: "shoukai", pos: "名詞" },
    { no: 208, en: "investment", ja: "とうし", romaji: "toushi", pos: "名詞" },
    { no: 209, en: "issue", ja: "もんだい", romaji: "mondai", pos: "名詞" },
    { no: 210, en: "job", ja: "しごと", romaji: "shigoto", pos: "名詞" },
    { no: 211, en: "knowledge", ja: "ちしき", romaji: "chishiki", pos: "名詞" },
    { no: 212, en: "lack", ja: "けつぼう", romaji: "ketsubou", pos: "名詞" },
    { no: 213, en: "lead", ja: "りーど", romaji: "riido", pos: "名詞" },
    { no: 214, en: "limit", ja: "げんかい", romaji: "genkai", pos: "名詞" },
    { no: 215, en: "line", ja: "らいん", romaji: "rain", pos: "名詞" },
    { no: 216, en: "list", ja: "りすと", romaji: "risuto", pos: "名詞" },
    { no: 217, en: "loss", ja: "そんしつ", romaji: "sonshitsu", pos: "名詞" },
    { no: 218, en: "maintenance", ja: "ほぜん", romaji: "hozen", pos: "名詞" },
    { no: 219, en: "manner", ja: "やりかた", romaji: "yarikata", pos: "名詞" },
    { no: 220, en: "material", ja: "ざいりょう", romaji: "zairyou", pos: "名詞" },
    { no: 221, en: "matter", ja: "もんだい", romaji: "mondai", pos: "名詞" },
    { no: 222, en: "means", ja: "しゅだん", romaji: "shudan", pos: "名詞" },
    { no: 223, en: "measure", ja: "そち", romaji: "sochi", pos: "名詞" },
    { no: 224, en: "member", ja: "めんばー", romaji: "menbaa", pos: "名詞" },
    { no: 225, en: "method", ja: "ほうほう", romaji: "houhou", pos: "名詞" },
    { no: 226, en: "minimum", ja: "さいしょう", romaji: "saishou", pos: "名詞" },
    { no: 227, en: "mistake", ja: "まちがい", romaji: "machigai", pos: "名詞" },
    { no: 228, en: "mode", ja: "もーど", romaji: "moodo", pos: "名詞" },
    { no: 229, en: "model", ja: "もでる", romaji: "moderu", pos: "名詞" },
    { no: 230, en: "need", ja: "ひつよう", romaji: "hitsuyou", pos: "名詞" },
    { no: 231, en: "negotiation", ja: "こうしょう", romaji: "koushou", pos: "名詞" },
    { no: 232, en: "network", ja: "ねっとわーく", romaji: "nettowaaku", pos: "名詞" },
    { no: 233, en: "objective", ja: "もくてき", romaji: "mokuteki", pos: "名詞" },
    { no: 234, en: "obligation", ja: "ぎむ", romaji: "gimu", pos: "名詞" },
    { no: 235, en: "operation", ja: "そうさ", romaji: "sousa", pos: "名詞" },
    { no: 236, en: "opportunity", ja: "きかい", romaji: "kikai", pos: "名詞" },
    { no: 237, en: "option", ja: "おぷしょん", romaji: "opushon", pos: "名詞" },
    { no: 238, en: "organization", ja: "そしき", romaji: "soshiki", pos: "名詞" },
    { no: 239, en: "outcome", ja: "けっか", romaji: "kekka", pos: "名詞" },
    { no: 240, en: "output", ja: "あうとぷっと", romaji: "autoputto", pos: "名詞" },
    { no: 241, en: "part", ja: "ぶぶん", romaji: "bubun", pos: "名詞" },
    { no: 242, en: "participant", ja: "さんかしゃ", romaji: "sankasha", pos: "名詞" },
    { no: 243, en: "partnership", ja: "ぱーとなーしっぷ", romaji: "paatonaashippu", pos: "名詞" },
    { no: 244, en: "percentage", ja: "ぱーせんと", romaji: "paasento", pos: "名詞" },
    { no: 245, en: "period", ja: "きかん", romaji: "kikan", pos: "名詞" },
    { no: 246, en: "permission", ja: "きょか", romaji: "kyoka", pos: "名詞" },
    { no: 247, en: "portion", ja: "ぶぶん", romaji: "bubun", pos: "名詞" },
    { no: 248, en: "position", ja: "ちい", romaji: "chii", pos: "名詞" },
    { no: 249, en: "possibility", ja: "かのうせい", romaji: "kanousei", pos: "名詞" },
    { no: 250, en: "practice", ja: "れんしゅう", romaji: "renshuu", pos: "名詞" }
];
