// Level 2（目標600点レベル）用単語リスト - 250語（TSL 251-500）
const vocabulary600 = [
    { no: 1, en: "accountant", ja: "かいけいし", romaji: "kaikeishi", pos: "名詞" },
    { no: 2, en: "appointment", ja: "よやく", romaji: "yoyaku", pos: "名詞" },
    { no: 3, en: "suggestion", ja: "ていあん", romaji: "teian", pos: "名詞" },
    { no: 4, en: "instruction", ja: "しじ", romaji: "shiji", pos: "名詞" },
    { no: 5, en: "delivery", ja: "はいとう", romaji: "haitou", pos: "名詞" },
    { no: 6, en: "manufacturer", ja: "せいぞうぎょうしゃ", romaji: "seizougyousha", pos: "名詞" },
    { no: 7, en: "recommendation", ja: "すいせん", romaji: "suisen", pos: "名詞" },
    { no: 8, en: "strategy", ja: "せんりゃく", romaji: "senryaku", pos: "名詞" },
    { no: 9, en: "resident", ja: "じゅうみん", romaji: "juumin", pos: "名詞" },
    { no: 10, en: "plant", ja: "こうじょう", romaji: "koujou", pos: "名詞" },
    { no: 11, en: "firm", ja: "かいしゃ", romaji: "kaisha", pos: "名詞" },
    { no: 12, en: "minute", ja: "ぎじろく", romaji: "gijiroku", pos: "名詞" },
    { no: 13, en: "applicable", ja: "てきようできる", romaji: "tekiyou dekiru", pos: "形容詞" },
    { no: 14, en: "cabinet", ja: "しょるいだな", romaji: "shoruidana", pos: "名詞" },
    { no: 15, en: "calculate", ja: "けいさんする", romaji: "keisan suru", pos: "動詞" },
    { no: 16, en: "cancellation", ja: "とりけし", romaji: "torikeshi", pos: "名詞" },
    { no: 17, en: "cargo", ja: "かもつ", romaji: "kamotsu", pos: "名詞" },
    { no: 18, en: "catering", ja: "しだし", romaji: "shidashi", pos: "名詞" },
    { no: 19, en: "clarify", ja: "めいかくにする", romaji: "meikaku ni suru", pos: "動詞" },
    { no: 20, en: "clerk", ja: "てんいん", romaji: "ten'in", pos: "名詞" },
    { no: 21, en: "consent", ja: "どうい", romaji: "doui", pos: "名詞" },
    { no: 22, en: "deduct", ja: "さしひく", romaji: "sashihiku", pos: "動詞" },
    { no: 23, en: "defective", ja: "けっかんのある", romaji: "kekkan no aru", pos: "形容詞" },
    { no: 24, en: "departure", ja: "しゅっぱつ", romaji: "shuppatsu", pos: "名詞" },
    { no: 25, en: "distribute", ja: "はいふする", romaji: "haifu suru", pos: "動詞" },
    { no: 26, en: "enclose", ja: "どうふする", romaji: "doufu suru", pos: "動詞" },
    { no: 27, en: "expansion", ja: "かくちょう", romaji: "kakuchou", pos: "名詞" },
    { no: 28, en: "inspection", ja: "けんさ", romaji: "kensa", pos: "名詞" },
    { no: 29, en: "inventory", ja: "ざいこ", romaji: "zaiko", pos: "名詞" },
    { no: 30, en: "invest", ja: "とうしする", romaji: "toushi suru", pos: "動詞" },
    { no: 31, en: "labor", ja: "ろうどう", romaji: "roudou", pos: "名詞" },
    { no: 32, en: "lease", ja: "ちんたい", romaji: "chintai", pos: "名詞" },
    { no: 33, en: "license", ja: "めんきょ", romaji: "menkyo", pos: "名詞" },
    { no: 34, en: "location", ja: "いち", romaji: "ichi", pos: "名詞" },
    { no: 35, en: "management", ja: "かんり", romaji: "kanri", pos: "名詞" },
    { no: 36, en: "manual", ja: "せつめいしょ", romaji: "setsumeisho", pos: "名詞" },
    { no: 37, en: "manufacture", ja: "せいぞうする", romaji: "seizou suru", pos: "動詞" },
    { no: 38, en: "material", ja: "ざいりょう", romaji: "zairyou", pos: "名詞" },
    { no: 39, en: "maximum", ja: "さいだい", romaji: "saidai", pos: "名詞" },
    { no: 40, en: "minimum", ja: "さいしょう", romaji: "saishou", pos: "名詞" },
    { no: 41, en: "negotiate", ja: "こうしょうする", romaji: "koushou suru", pos: "動詞" },
    { no: 42, en: "operation", ja: "そうさ", romaji: "sousa", pos: "名詞" },
    { no: 43, en: "obtain", ja: "える", romaji: "eru", pos: "動詞" },
    { no: 44, en: "operate", ja: "うんえいする", romaji: "un'ei suru", pos: "動詞" },
    { no: 45, en: "original", ja: "げんぽんの", romaji: "genpon no", pos: "形容詞" },
    { no: 46, en: "package", ja: "こづつみ", romaji: "kozutsumi", pos: "名詞" },
    { no: 47, en: "participant", ja: "さんかしゃ", romaji: "sankasha", pos: "名詞" },
    { no: 48, en: "participate", ja: "さんかする", romaji: "sanka suru", pos: "動詞" },
    { no: 49, en: "partnership", ja: "きょうどう", romaji: "kyoudou", pos: "名詞" },
    { no: 50, en: "percentage", ja: "ぱーせんと", romaji: "paasento", pos: "名詞" },
    { no: 51, en: "portion", ja: "ぶぶん", romaji: "bubun", pos: "名詞" },
    { no: 52, en: "postpone", ja: "えんきする", romaji: "enki suru", pos: "動詞" },
    { no: 53, en: "prefer", ja: "このむ", romaji: "konomu", pos: "動詞" },
    { no: 54, en: "premium", ja: "ほけんりょう", romaji: "hokenryou", pos: "名詞" },
    { no: 55, en: "present", ja: "ていじする", romaji: "teiji suru", pos: "動詞" },
    { no: 56, en: "produce", ja: "せいさんする", romaji: "seisan suru", pos: "動詞" },
    { no: 57, en: "progress", ja: "しんちょく", romaji: "shinchoku", pos: "名詞" },
    { no: 58, en: "promote", ja: "そくしんする", romaji: "sokushin suru", pos: "動詞" },
    { no: 59, en: "qualify", ja: "しかくをえる", romaji: "shikaku wo eru", pos: "動詞" },
    { no: 60, en: "quote", ja: "みつもり", romaji: "mitsumori", pos: "名詞" },
    { no: 61, en: "refer", ja: "さんしょうする", romaji: "sanshou suru", pos: "動詞" },
    { no: 62, en: "register", ja: "とうろくする", romaji: "touroku suru", pos: "動詞" },
    { no: 63, en: "retail", ja: "こうり", romaji: "kouri", pos: "名詞" },
    { no: 64, en: "software", ja: "そふとうぇあ", romaji: "sofutouea", pos: "名詞" },
    { no: 65, en: "subsidiary", ja: "こがいしゃ", romaji: "kogaisha", pos: "名詞" },
    { no: 66, en: "supplier", ja: "きょうきゅうしゃ", romaji: "kyoukyuusha", pos: "名詞" },
    { no: 67, en: "transaction", ja: "とりひき", romaji: "torihiki", pos: "名詞" },
    { no: 68, en: "warranty", ja: "ほしょう", romaji: "hoshou", pos: "名詞" },
    { no: 69, en: "attendance", ja: "しゅっせき", romaji: "shusseki", pos: "名詞" },
    { no: 70, en: "authorize", ja: "きょかする", romaji: "kyoka suru", pos: "動詞" },
    { no: 71, en: "automate", ja: "じどうかする", romaji: "jidouka suru", pos: "動詞" },
    { no: 72, en: "compliance", ja: "じゅんしゅ", romaji: "junshu", pos: "名詞" },
    { no: 73, en: "confidential", ja: "きみつの", romaji: "kimitsu no", pos: "形容詞" },
    { no: 74, en: "consolidate", ja: "とうごうする", romaji: "tougou suru", pos: "動詞" },
    { no: 75, en: "coordinate", ja: "ちょうせいする", romaji: "chousei suru", pos: "動詞" },
    { no: 76, en: "delegate", ja: "いにんする", romaji: "inin suru", pos: "動詞" },
    { no: 77, en: "demonstrate", ja: "じつえんする", romaji: "jitsuen suru", pos: "動詞" },
    { no: 78, en: "documentation", ja: "しょるいか", romaji: "shorui ka", pos: "名詞" },
    { no: 79, en: "eligible", ja: "しかくのある", romaji: "shikaku no aru", pos: "形容詞" },
    { no: 80, en: "establish", ja: "せつりつする", romaji: "setsuritsu suru", pos: "動詞" },
    { no: 81, en: "expertise", ja: "せんもんちしき", romaji: "senmon chishiki", pos: "名詞" },
    { no: 82, en: "facilitate", ja: "えんかつにする", romaji: "enkatsu ni suru", pos: "動詞" },
    { no: 83, en: "administer", ja: "かんりする", romaji: "kanri suru", pos: "動詞" },
    { no: 84, en: "incentive", ja: "どうきづけ", romaji: "doukizuke", pos: "名詞" },
    { no: 85, en: "infrastructure", ja: "きばん", romaji: "kiban", pos: "名詞" },
    { no: 86, en: "innovative", ja: "かくしんてきな", romaji: "kakushinteki na", pos: "形容詞" },
    { no: 87, en: "liaison", ja: "れんらくやく", romaji: "renrakuyaku", pos: "名詞" },
    { no: 88, en: "mandatory", ja: "ひっすの", romaji: "hissu no", pos: "形容詞" },
    { no: 89, en: "optimize", ja: "さいてきかする", romaji: "saiteki ka suru", pos: "動詞" },
    { no: 90, en: "prioritize", ja: "ゆうせんする", romaji: "yuusen suru", pos: "動詞" },
    { no: 91, en: "protocol", ja: "てじゅん", romaji: "tejun", pos: "名詞" },
    { no: 92, en: "qualification", ja: "しかく", romaji: "shikaku", pos: "名詞" },
    { no: 93, en: "redundant", ja: "よぶんな", romaji: "yobun na", pos: "形容詞" },
    { no: 94, en: "regulatory", ja: "きせいの", romaji: "kisei no", pos: "形容詞" },
    { no: 95, en: "streamline", ja: "ごうりかする", romaji: "gourika suru", pos: "動詞" },
    { no: 96, en: "terminate", ja: "しゅうりょうする", romaji: "shuuryou suru", pos: "動詞" },
    { no: 97, en: "valid", ja: "ゆうこうな", romaji: "yuukou na", pos: "形容詞" },
    { no: 98, en: "verify", ja: "かくにんする", romaji: "kakunin suru", pos: "動詞" },
    { no: 99, en: "accommodate", ja: "しゅうようする", romaji: "shuuyou suru", pos: "動詞" },
    { no: 100, en: "acknowledge", ja: "みとめる", romaji: "mitomeru", pos: "動詞" },
    { no: 101, en: "requirement", ja: "ようきゅう", romaji: "youkyuu", pos: "名詞" },
    { no: 102, en: "reservation", ja: "よやく", romaji: "yoyaku", pos: "名詞" },
    { no: 103, en: "retail", ja: "こうり", romaji: "kouri", pos: "名詞" },
    { no: 104, en: "software", ja: "そふとうぇあ", romaji: "sofutouea", pos: "名詞" },
    { no: 105, en: "subsidiary", ja: "こがいしゃ", romaji: "kogaisha", pos: "名詞" },
    { no: 106, en: "supplier", ja: "きょうきゅうしゃ", romaji: "kyoukyuusha", pos: "名詞" },
    { no: 107, en: "transaction", ja: "とりひき", romaji: "torihiki", pos: "名詞" },
    { no: 108, en: "warehouse", ja: "そうこ", romaji: "souko", pos: "名詞" },
    { no: 109, en: "warranty", ja: "ほしょう", romaji: "hoshou", pos: "名詞" },
    { no: 110, en: "attendance", ja: "しゅっせき", romaji: "shusseki", pos: "名詞" },
    { no: 111, en: "authorize", ja: "けんきをあたえる", romaji: "kenki wo ataeru", pos: "動詞" },
    { no: 112, en: "automate", ja: "じどうかする", romaji: "jidouka suru", pos: "動詞" },
    { no: 113, en: "compliance", ja: "じゅんしゅ", romaji: "junshu", pos: "名詞" },
    { no: 114, en: "confidential", ja: "きみつの", romaji: "kimitsu no", pos: "形容詞" },
    { no: 115, en: "consolidate", ja: "とうごうする", romaji: "tougou suru", pos: "動詞" },
    { no: 116, en: "coordinate", ja: "とりまとめる", romaji: "torimatomeru", pos: "動詞" },
    { no: 117, en: "delegate", ja: "いにんする", romaji: "inin suru", pos: "動詞" },
    { no: 118, en: "demonstrate", ja: "じっこうしてしめす", romaji: "jikkou shite shimesu", pos: "動詞" },
    { no: 119, en: "documentation", ja: "しょるいか", romaji: "shorui ka", pos: "名詞" },
    { no: 120, en: "eligible", ja: "しかくのある", romaji: "shikaku no aru", pos: "形容詞" },
    { no: 121, en: "establish", ja: "せつりつする", romaji: "setsuritsu suru", pos: "動詞" },
    { no: 122, en: "expertise", ja: "せんもんちしき", romaji: "senmon chishiki", pos: "名詞" },
    { no: 123, en: "facilitate", ja: "じゅんちょうにする", romaji: "junchou ni suru", pos: "動詞" },
    { no: 124, en: "implement", ja: "じっしする", romaji: "jisshi suru", pos: "動詞" },
    { no: 125, en: "incentive", ja: "しどうきん", romaji: "shidoukin", pos: "名詞" },
    { no: 126, en: "infrastructure", ja: "きそしせつ", romaji: "kiso shisetsu", pos: "名詞" },
    { no: 127, en: "innovative", ja: "かくしんてきな", romaji: "kakushinteki na", pos: "形容詞" },
    { no: 128, en: "liaison", ja: "れんらくやく", romaji: "renrakuyaku", pos: "名詞" },
    { no: 129, en: "mandatory", ja: "ひっすの", romaji: "hissu no", pos: "形容詞" },
    { no: 130, en: "optimize", ja: "さいてきかする", romaji: "saiteki ka suru", pos: "動詞" },
    { no: 131, en: "prioritize", ja: "ゆうせんじゅんいをつける", romaji: "yuusen jun'i wo tsukeru", pos: "動詞" },
    { no: 132, en: "protocol", ja: "ぎょうれつ", romaji: "gyouretsu", pos: "名詞" },
    { no: 133, en: "qualification", ja: "しかく", romaji: "shikaku", pos: "名詞" },
    { no: 134, en: "redundant", ja: "じゅうふくな", romaji: "juufuku na", pos: "形容詞" },
    { no: 135, en: "regulatory", ja: "きせいの", romaji: "kisei no", pos: "形容詞" },
    { no: 136, en: "streamline", ja: "こうりゅうかする", romaji: "kouryuuka suru", pos: "動詞" },
    { no: 137, en: "submit", ja: "ていしゅつする", romaji: "teishutsu suru", pos: "動詞" },
    { no: 138, en: "terminate", ja: "しゅうりょうする", romaji: "shuuryou suru", pos: "動詞" },
    { no: 139, en: "valid", ja: "ゆうこうな", romaji: "yuukou na", pos: "形容詞" },
    { no: 140, en: "verify", ja: "かくにんする", romaji: "kakunin suru", pos: "動詞" },
    { no: 141, en: "accommodate", ja: "うけいれる", romaji: "ukeireru", pos: "動詞" },
    { no: 142, en: "acknowledge", ja: "みとめる", romaji: "mitomeru", pos: "動詞" },
    { no: 143, en: "adjourn", ja: "えんきする", romaji: "enki suru", pos: "動詞" },
    { no: 144, en: "allocate", ja: "わりあてる", romaji: "wariateru", pos: "動詞" },
    { no: 145, en: "amend", ja: "しゅうせいする", romaji: "shuusei suru", pos: "動詞" },
    { no: 146, en: "anticipate", ja: "よそうする", romaji: "yosou suru", pos: "動詞" },
    { no: 147, en: "assemble", ja: "あつめる", romaji: "atsumeru", pos: "動詞" },
    { no: 148, en: "assess", ja: "ひょうかする", romaji: "hyouka suru", pos: "動詞" },
    { no: 149, en: "assist", ja: "ほじょする", romaji: "hojo suru", pos: "動詞" },
    { no: 150, en: "assume", ja: "かんがえる", romaji: "kangaeru", pos: "動詞" },
    { no: 151, en: "assure", ja: "ほあんする", romaji: "hoan suru", pos: "動詞" },
    { no: 152, en: "audit", ja: "かんさする", romaji: "kansa suru", pos: "動詞" },
    { no: 153, en: "avoid", ja: "さける", romaji: "sakeru", pos: "動詞" },
    { no: 154, en: "clarify", ja: "めいかくにする", romaji: "meikaku ni suru", pos: "動詞" },
    { no: 155, en: "collaborate", ja: "きょうりょくする", romaji: "kyouryoku suru", pos: "動詞" },
    { no: 156, en: "commence", ja: "かいしする", romaji: "kaishi suru", pos: "動詞" },
    { no: 157, en: "compensate", ja: "ほしょうする", romaji: "hoshou suru", pos: "動詞" },
    { no: 158, en: "complement", ja: "ほきょうする", romaji: "hokyou suru", pos: "動詞" },
    { no: 159, en: "comply", ja: "したがう", romaji: "shitagau", pos: "動詞" },
    { no: 160, en: "convene", ja: "しゅうごうする", romaji: "shuugou suru", pos: "動詞" },
    { no: 161, en: "convey", ja: "つたえる", romaji: "tsutaeru", pos: "動詞" },
    { no: 162, en: "deduct", ja: "さしひく", romaji: "sashihiku", pos: "動詞" },
    { no: 163, en: "defer", ja: "えんきする", romaji: "enki suru", pos: "動詞" },
    { no: 164, en: "delete", ja: "さくじょする", romaji: "sakujo suru", pos: "動詞" },
    { no: 165, en: "designate", ja: "していする", romaji: "shitei suru", pos: "動詞" },
    { no: 166, en: "dispose", ja: "しょりする", romaji: "shori suru", pos: "動詞" },
    { no: 167, en: "distinguish", ja: "くべつする", romaji: "kubetsu suru", pos: "動詞" },
    { no: 168, en: "dominate", ja: "しはいする", romaji: "shihai suru", pos: "動詞" },
    { no: 169, en: "eliminate", ja: "のぞく", romaji: "nozoku", pos: "動詞" },
    { no: 170, en: "emphasize", ja: "きょうちょうする", romaji: "kyouchou suru", pos: "動詞" },
    { no: 171, en: "enable", ja: "可能にする", romaji: "kanou ni suru", pos: "動詞" },
    { no: 172, en: "enforce", ja: "きょうせいする", romaji: "kyousei suru", pos: "動詞" },
    { no: 173, en: "engage", ja: "かかわる", romaji: "kakawaru", pos: "動詞" },
    { no: 174, en: "enhance", ja: "こうじょうする", romaji: "koujou suru", pos: "動詞" },
    { no: 175, en: "exceed", ja: "こえる", romaji: "koeru", pos: "動詞" },
    { no: 176, en: "execute", ja: "じっこうする", romaji: "jikkou suru", pos: "動詞" },
    { no: 177, en: "expedite", ja: "すみやかにする", romaji: "sumiyaka ni suru", pos: "動詞" },
    { no: 178, en: "export", ja: "ゆしゅつする", romaji: "yushutsu suru", pos: "動詞" },
    { no: 179, en: "extend", ja: "のばす", romaji: "nobasu", pos: "動詞" },
    { no: 180, en: "finalize", ja: "けっていする", romaji: "kettei suru", pos: "動詞" },
    { no: 181, en: "formalize", ja: "かたちかする", romaji: "katachika suru", pos: "動詞" },
    { no: 182, en: "generate", ja: "せいせいする", romaji: "seisei suru", pos: "動詞" },
    { no: 183, en: "grant", ja: "じゅよする", romaji: "juyo suru", pos: "動詞" },
    { no: 184, en: "highlight", ja: "ひょうめいする", romaji: "hyoumei suru", pos: "動詞" },
    { no: 185, en: "impose", ja: "かすする", romaji: "kasu suru", pos: "動詞" },
    { no: 186, en: "incorporate", ja: "とりこむ", romaji: "torikomu", pos: "動詞" },
    { no: 187, en: "indicate", ja: "しめす", romaji: "shimesu", pos: "動詞" },
    { no: 188, en: "inform", ja: "つたえる", romaji: "tsutaeru", pos: "動詞" },
    { no: 189, en: "initiate", ja: "かいしする", romaji: "kaishi suru", pos: "動詞" },
    { no: 190, en: "insert", ja: "そうにゅうする", romaji: "sounyuu suru", pos: "動詞" },
    { no: 191, en: "inspect", ja: "けんさする", romaji: "kensa suru", pos: "動詞" },
    { no: 192, en: "install", ja: "せつびする", romaji: "setsubi suru", pos: "動詞" },
    { no: 193, en: "integrate", ja: "せつごうする", romaji: "setsugou suru", pos: "動詞" },
    { no: 194, en: "interpret", ja: "かいしゃくする", romaji: "kaishaku suru", pos: "動詞" },
    { no: 195, en: "intervene", ja: "かいにゅうする", romaji: "kainyuu suru", pos: "動詞" },
    { no: 196, en: "introduce", ja: "しょうかいする", romaji: "shoukai suru", pos: "動詞" },
    { no: 197, en: "involve", ja: "かかわる", romaji: "kakawaru", pos: "動詞" },
    { no: 198, en: "justify", ja: "せいとうかする", romaji: "seitouka suru", pos: "動詞" },
    { no: 199, en: "launch", ja: "ろーんちする", romaji: "roonchi suru", pos: "動詞" },
    { no: 200, en: "locate", ja: "いちをさだめる", romaji: "ichi wo sadameru", pos: "動詞" },
    { no: 201, en: "maximize", ja: "さいだいかする", romaji: "saidai ka suru", pos: "動詞" },
    { no: 202, en: "minimize", ja: "さいしょうかする", romaji: "saishou ka suru", pos: "動詞" },
    { no: 203, en: "modify", ja: "しゅうせいする", romaji: "shuusei suru", pos: "動詞" },
    { no: 204, en: "monitor", ja: "かんしする", romaji: "kanshi suru", pos: "動詞" },
    { no: 205, en: "obtain", ja: "える", romaji: "eru", pos: "動詞" },
    { no: 206, en: "operate", ja: "うんえいする", romaji: "un'ei suru", pos: "動詞" },
    { no: 207, en: "organize", ja: "そしきする", romaji: "soshiki suru", pos: "動詞" },
    { no: 208, en: "outline", ja: "あらすじ", romaji: "arasuji", pos: "名詞" },
    { no: 209, en: "overcome", ja: "こくふくする", romaji: "kokufuku suru", pos: "動詞" },
    { no: 210, en: "participate", ja: "さんかする", romaji: "sanka suru", pos: "動詞" },
    { no: 211, en: "perform", ja: "おこなう", romaji: "okonau", pos: "動詞" },
    { no: 212, en: "prepare", ja: "じゅんびする", romaji: "junbi suru", pos: "動詞" },
    { no: 213, en: "present", ja: "ていしゅつする", romaji: "teishutsu suru", pos: "動詞" },
    { no: 214, en: "prevent", ja: "ふせぐ", romaji: "fusegu", pos: "動詞" },
    { no: 215, en: "produce", ja: "せいさんする", romaji: "seisan suru", pos: "動詞" },
    { no: 216, en: "promote", ja: "そうしんする", romaji: "soushin suru", pos: "動詞" },
    { no: 217, en: "provide", ja: "ていきょうする", romaji: "teikyou suru", pos: "動詞" },
    { no: 218, en: "purchase", ja: "こうにゅうする", romaji: "kounyuu suru", pos: "動詞" },
    { no: 219, en: "pursue", ja: "ついきゅうする", romaji: "tsuikyuu suru", pos: "動詞" },
    { no: 220, en: "qualify", ja: "しかくをえる", romaji: "shikaku wo eru", pos: "動詞" },
    { no: 221, en: "receive", ja: "うけとる", romaji: "uketoru", pos: "動詞" },
    { no: 222, en: "recommend", ja: "すいせんする", romaji: "suisen suru", pos: "動詞" },
    { no: 223, en: "reduce", ja: "へらす", romaji: "herasu", pos: "動詞" },
    { no: 224, en: "refer", ja: "さんしょうする", romaji: "sanshou suru", pos: "動詞" },
    { no: 225, en: "register", ja: "とうろくする", romaji: "touroku suru", pos: "動詞" },
    { no: 226, en: "regulate", ja: "きせいする", romaji: "kisei suru", pos: "動詞" },
    { no: 227, en: "reinforce", ja: "きょうかする", romaji: "kyouka suru", pos: "動詞" },
    { no: 228, en: "reject", ja: "きょぜつする", romaji: "kyozetsu suru", pos: "動詞" },
    { no: 229, en: "release", ja: "りりーすする", romaji: "ririisu suru", pos: "動詞" },
    { no: 230, en: "remain", ja: "のこる", romaji: "nokoru", pos: "動詞" },
    { no: 231, en: "remove", ja: "とりのぞく", romaji: "torinozoku", pos: "動詞" },
    { no: 232, en: "replace", ja: "おきかえる", romaji: "okikaeru", pos: "動詞" },
    { no: 233, en: "represent", ja: "だいひょうする", romaji: "daihyou suru", pos: "動詞" },
    { no: 234, en: "resolve", ja: "かいけつする", romaji: "kaiketsu suru", pos: "動詞" },
    { no: 235, en: "respond", ja: "へんじする", romaji: "henji suru", pos: "動詞" },
    { no: 236, en: "restrict", ja: "せいげんする", romaji: "seigen suru", pos: "動詞" },
    { no: 237, en: "retain", ja: "ほじする", romaji: "hoji suru", pos: "動詞" },
    { no: 238, en: "revise", ja: "しゅうせいする", romaji: "shuusei suru", pos: "動詞" },
    { no: 239, en: "select", ja: "えらぶ", romaji: "erabu", pos: "動詞" },
    { no: 240, en: "separate", ja: "ぶんりする", romaji: "bunri suru", pos: "動詞" },
    { no: 241, en: "settle", ja: "けっさいする", romaji: "kessai suru", pos: "動詞" },
    { no: 242, en: "simplify", ja: "かんりょうする", romaji: "kanryou suru", pos: "動詞" },
    { no: 243, en: "solve", ja: "かいけつする", romaji: "kaiketsu suru", pos: "動詞" },
    { no: 244, en: "specify", ja: "していする", romaji: "shitei suru", pos: "動詞" },
    { no: 245, en: "spend", ja: "つかう", romaji: "tsukau", pos: "動詞" },
    { no: 246, en: "standardize", ja: "ひょうじゅんかする", romaji: "hyoujunka suru", pos: "動詞" },
    { no: 247, en: "summarize", ja: "ようやくする", romaji: "youyaku suru", pos: "動詞" },
    { no: 248, en: "supply", ja: "きょうきゅうする", romaji: "kyoukyuu suru", pos: "動詞" },
    { no: 249, en: "train", ja: "くんれんする", romaji: "kunren suru", pos: "動詞" },
    { no: 250, en: "transform", ja: "へんかんする", romaji: "henkan suru", pos: "動詞" }
];
const wordList630 = vocabulary600;
